/* La consola en tres idiomas.

   Centauro opera en Mexico y Brasil, y el consultor que atiende a un
   cliente extranjero trabaja mas comodo en el idioma del cliente. La
   bandera de la barra cambia toda la consola y se queda puesta la
   sesion entera.

   El texto vive aqui, en un solo lugar: una pantalla nueva agrega sus
   claves a esta tabla y queda en los tres idiomas de una vez. Lo que no
   este traducido cae al espanol, que es como esta escrito el sistema:
   mas vale una palabra en espanol dentro de una pantalla en ingles que
   un hueco. */

const LLAVE = "centauro_idioma";

export const IDIOMAS = [
  // Mexico, no España: es donde opera Centauro y donde esta su gente.
  { codigo: "es", bandera: "🇲🇽", nombre: "Español" },
  { codigo: "en", bandera: "🇺🇸", nombre: "English" },
  { codigo: "pt", bandera: "🇧🇷", nombre: "Português" },
];

/* El espanol es la base: es el idioma en que se escribe el sistema y el
   que ven quienes lo operan todos los dias. */
const TEXTOS = {
  es: {
    /* --- barra y acceso */
    linea: "Proteccion Ejecutiva",
    correo: "Correo",
    contrasena: "Contrasena",
    entrar: "Entrar",
    salir: "Salir",
    nav_operacion: "Operacion",
    nav_eventuales: "EP eventual",
    nav_implantados: "EP implantado",
    implantados_titulo: "Servicios implantados",
    implantados_sub: "Continuos: un renglon por servicio, no por mes.",
    sin_implantados: "Todavia no hay implantados.",
    nuevo_implantado: "Nuevo implantado",
    imp_alta_titulo: "Nuevo servicio implantado",
    imp_alta_sub: "Se captura una vez: el trato no cambia y cada mes se abre solo.",
    imp_trato: "El acuerdo",
    imp_trato_sub: "Esto es lo que no cambia de mes a mes. De aqui sale el task sheet.",
    imp_punto_fijo: "Punto fijo (meet and greet)",
    imp_lat: "Latitud",
    imp_lon: "Longitud",
    imp_geocerca: "Geocerca (m)",
    imp_dias_semana: "Dias de la semana",
    imp_dias_lv: "Lunes a viernes",
    imp_dias_ej: "Ej: lunes a viernes",
    imp_hora: "Hora de presentacion",
    imp_zona: "Zona de operacion",
    imp_zona_buscar: "Busca",
    imp_zona_generico: "municipios y zonas",
    imp_zona_a_mano: "Google no contesto. Escribe la zona y se toma tal cual.",
    imp_ciudad_a_mano: "Google no contesto. Intenta de nuevo en un momento.",
    buscar_ciudad: "Busca la ciudad en Google",
    ciudad_sin_google: "Google no contesto. Intenta de nuevo en un momento.",
    imp_zona_ej: "Ej: Valle de Mexico, sin salir a carretera",
    imp_cubre: "Acuerdos",
    imp_cubre_ej: "Lo que se acordo con el cliente: horario, descansos, quien autoriza cambios.",
    imp_no_cubre: "Alcance del servicio",
    imp_no_cubre_ej: "Hasta donde llega el servicio y que queda fuera.",
    imp_reporta: "Coordinacion del servicio",
    imp_protocolo: "Protocolo especial del servicio",
    /* El recuadro va vacio y la guia se lee en gris adentro: lo que hay
       que escribir ahi no se adivina, y un recuadro en blanco con un
       titulo se queda en blanco. */
    imp_protocolo_ej:
      "Como y a que hora avisa que llego, y por que canal: WhatsApp al grupo, "
      + "llamada a la asistente, mensaje a seguridad corporativa.\n"
      + "Quien puede cambiar la ruta o el horario sobre la marcha.\n"
      + "Que hacer si el ejecutivo no baja a la hora o cancela sin avisar: "
      + "cuanto espera y a quien le marca.\n"
      + "Reglas de la casa del cliente: si entra al estacionamiento o espera "
      + "afuera, si puede dejar la unidad, si hay caseta con registro previo.\n"
      + "Ante una incidencia: a quien se le avisa primero, si el cliente "
      + "quiere enterarse antes que la central.",
    imp_mes: "El primer mes",
    imp_asignacion: "Asignacion y coordinacion",
    imp_volver: "Volver a la cartera",
    imp_no_existe: "Ese servicio no existe o no es implantado.",
    imp_abrir_mes: "Abrir el primer mes",
    imp_cargando: "Un momento...",
    imp_liberar: "Liberar la hoja",
    imp_liberada: "hoja liberada, version",
    imp_ts_nota: "La hoja se arma con lo ultimo capturado: cada boton la "
      + "vuelve a generar.",
    imp_ventana_bloqueada: "El navegador bloqueo la ventana de la hoja.",
    imp_sin_gente_ciudad: "No hay personal de seguridad dado de alta en esa "
      + "ciudad. Se carga en Personal, o se cambia la ciudad del servicio.",
    imp_sin_flota_ciudad: "No hay unidades en esa ciudad.",
    imp_col_posicion: "Posicion del mes",
    imp_col_cubre: "Quien lo cubre",
    imp_del_equipo: "del equipo",
    imp_ocupado: "ocupado ese dia",
    imp_abrir_dia: "Abrir el dia",
    imp_cubrir_dia: "Guardar quien lo cubre",
    imp_cerrar_dia: "Cerrar el dia",
    imp_dia_guardado: "Dia cubierto.",
    imp_dia_cerrado: "Dia cerrado.",
    imp_todo_el_fin: "Cubrir tambien el",
    imp_sin_plantilla: "El mes no tiene plantilla.",
    imp_editar: "Editar",
    imp_guardar: "Guardar cambios",
    imp_acuerdo_corregido: "Acuerdo actualizado.",
    imp_sin_arranque: "Este servicio no tiene dia de arranque. Ponlo aqui "
      + "para poder abrir el mes.",
    imp_arranque_guardado: "Dia de arranque guardado.",
    imp_por_cubrir_aviso: "dias del mes sin quien los cubra",
    imp_bloqueo_asignacion: "Primero el cliente y el acuerdo. Falta:",
    imp_cobro: "Como se cobra el mes",
    imp_guardar_acuerdo: "Guardar cliente y acuerdo",
    imp_acuerdo_guardado: "guardado. Ya tiene folio; la asignacion se puede "
      + "terminar despues.",
    imp_mes_sub: "El corte cae el ultimo dia del mes; el siguiente empieza el dia 1.",
    imp_anio: "Anio",
    imp_fecha_inicio: "Dia de inicio del servicio",
    imp_dias_servicio: "Dias de servicio",
    imp_lunes_viernes: "Lunes a viernes",
    imp_lunes_sabado: "Lunes a sabado",
    imp_todos_los_dias: "Todos los dias",
    imp_calendario: "El mes",
    imp_sin_fecha: "Pon la fecha de arranque para ver el mes.",
    imp_dia_cubierto: "Cubierto por el equipo del servicio",
    imp_dia_por_cubrir: "Contratado: falta decir quien lo cubre",
    imp_dia_sin_servicio: "Sin servicio contratado",
    imp_dia_antes: "Antes de que arranque el servicio",
    imp_dia_abierto: "Abierto a mano: lo cubre el mismo equipo",
    imp_dia_se_puede_abrir: "Sin contratar. Click para abrirlo con el mismo equipo",
    imp_calendario_ayuda: "El calendario sale de los dias de servicio "
      + "acordados arriba. Los fines de semana contratados quedan en ambar "
      + "hasta que se diga quien los cubre, y eso se hace en el panel del "
      + "mes, con el servicio ya corriendo.",
    imp_leyenda_verde: "Cubierto",
    imp_leyenda_ambar: "Falta quien lo cubra",
    imp_leyenda_gris: "Sin servicio",
    imp_falta_fecha: "Fecha en que arranca el servicio",
    imp_mes_campo: "Mes",
    imp_desde_dia: "Arranca el dia",
    imp_desde_ej: "Vacio: mes completo",
    imp_modalidad: "Modalidad",
    imp_sin_modalidad: "Este pais no tiene dia completo en el catalogo",
    imp_esquema: "Como se cobra",
    imp_por_dia: "Por dia trabajado",
    imp_mes_completo: "Un precio por el mes",
    imp_fines_de_semana: "Incluye fines de semana",
    imp_precio_mes_vehiculo: "Vehiculo al mes",
    imp_precio_dia_personal: "Personal por dia",
    imp_precio_dia_adicional: "Dia adicional",
    imp_precio_mes_completo: "Precio del mes",
    imp_plantilla: "La plantilla del mes",
    imp_plantilla_sub: "Cualquier combinacion, con dos reglas: por lo menos una "
      + "persona de seguridad, y toda unidad con la suya.",
    imp_elige_persona: "Elige a quien va",
    imp_col_persona: "Persona de seguridad",
    imp_col_categoria_persona: "Categoria",
    imp_elige_categoria_persona: "Primero la categoria",
    imp_col_categoria: "Categoria de unidad",
    imp_elige_categoria: "Primero la categoria",
    imp_elige_unidad: "Elige la unidad",
    imp_libre: "libre",
    imp_sin_unidad: "Sin unidad",
    imp_agregar_persona: "Agregar persona",
    imp_agregar_unidad: "Agregar unidad",
    imp_unidades: "Unidades",
    imp_col_lleva: "Quien la lleva",
    imp_elige_conductor: "Elige quien la lleva",
    imp_falta: "Falta para dar de alta",
    imp_falta_modalidad: "Modalidad del servicio",
    imp_falta_punto: "Punto fijo donde se presenta",
    imp_falta_plantilla: "Por lo menos una persona en la plantilla",
    imp_dar_alta: "Dar de alta el implantado",
    imp_dias_armados: "dias armados",
    imp_meses_abiertos: "Meses abiertos",
    imp_sin_meses: "Este servicio todavia no tiene ningun mes abierto",
    imp_viaticos: "Viaticos del mes",
    imp_taller: "Unidad al taller",
    imp_hospitales: "Hospitales de referencia",
    imp_tabulador: "Tabulador de viaticos",
    imp_elige_rol: "Elige el rol…",
    imp_col_rol: "Rol",
    imp_rol_sub: "El rol es de la tarea. El personal de seguridad es general: "
                 + "el mismo agente que hoy conduce manana coordina, y del rol "
                 + "salen lo que se cobra y lo que se le paga.",
    imp_tab_sub: "Lo que se acordo con este cliente, por dia y por persona. "
                 + "El implantado se negocia uno por uno, asi que este "
                 + "tabulador es de este acuerdo y de ningun otro.",
    imp_tab_concepto: "Concepto",
    imp_tab_monto: "Por dia",
    imp_tab_abierto: "Monto abierto",
    imp_tab_abierto_ayuda: "Existe, pero el monto se captura el dia que toca",
    imp_tab_nota: "Nota",
    imp_tab_va: "Va",
    imp_tab_sugerido: "la empresa sugiere",
    imp_tab_total: "Total por dia y por persona",
    imp_tab_guardar: "Guardar el tabulador",
    imp_tab_guardado: "Tabulador guardado",
    imp_tab_vacio: "Este acuerdo todavia no tiene tabulador. Sin el, la "
                   + "propuesta de viaticos del mes sale en cero.",
    imp_tab_alimentos: "Alimentos",
    imp_tab_traslado: "Traslado del personal",
    imp_tab_combustible: "Combustible",
    imp_tab_casetas: "Casetas",
    imp_tab_hospedaje: "Hospedaje",
    imp_tab_otros: "Otros",
    imp_hospitales_sub: "Los tres mas cercanos al punto del servicio, de su "
                        + "ciudad. Es lo que va a leer el equipo en una "
                        + "emergencia.",
    imp_hosp_vacio: "Esta ciudad no tiene hospitales cargados. La hoja saldria "
                    + "sin referencia medica.",
    imp_hosp_sin_punto: "Sin el punto del servicio no se pueden buscar.",
    imp_hosp_buscar: "Buscar cerca en Google",
    imp_hosp_nivel: "Nivel de atencion",
    imp_hosp_primero: "Primer nivel (estabiliza y refiere)",
    imp_hosp_segundo: "Segundo nivel",
    imp_hosp_tercero: "Tercer nivel (quirofano)",
    imp_hosp_agregar: "Agregar al catalogo",
    imp_hosp_ya: "Ya esta en el catalogo",
    imp_hosp_falta_nivel: "Marque el nivel. Google no lo sabe y no se adivina.",
    imp_hosp_agregado: "quedo en el catalogo de la ciudad",
    imp_hosp_nota: "Google llena el nombre, la direccion, el telefono y las "
                   + "coordenadas. El nivel lo marca Centauro una sola vez: de "
                   + "ahi sale la regla que garantiza un quirofano.",
    imp_taller_sub: "La unidad sale de circulacion y otra toma su lugar en "
                    + "los dias del tramo. El bloqueo vale para toda la "
                    + "empresa, no solo para este servicio.",
    imp_taller_sale: "Unidad que sale",
    imp_taller_entra: "Unidad que entra",
    imp_taller_desde: "Desde",
    imp_taller_hasta: "Hasta (opcional)",
    imp_taller_tipo: "Motivo",
    imp_taller_preventivo: "Mantenimiento preventivo",
    imp_taller_correctivo: "Mantenimiento correctivo",
    imp_taller_donde: "Taller",
    imp_taller_folio: "Folio de la orden",
    imp_taller_nota: "Nota",
    imp_taller_guardar: "Meter al taller",
    imp_taller_libre: "libre",
    imp_taller_de: "de",
    imp_taller_hecho: "quedo fuera de circulacion; la cubre",
    imp_taller_fuera: "Fuera de circulacion hoy",
    imp_taller_sin_fecha: "sin fecha de entrega",
    imp_taller_abrir: "Meter una unidad al taller",
    imp_taller_cerrar: "Cerrar",
    imp_taller_falta: "Diga que unidad entra",
    imp_viaticos_sub: "Un deposito por persona, por sus dias de este mes. "
                      + "El sistema propone segun el tabulador; el monto lo "
                      + "decide usted. El cierre es mensual.",
    imp_vi_persona: "Persona",
    imp_vi_propone: "Propone el sistema",
    imp_vi_deposita: "Se deposita",
    imp_vi_mas: "Se deposita mas",
    imp_vi_estado: "Estado",
    imp_vi_dias: "dias",
    imp_vi_guardar: "Guardar",
    imp_vi_solicitar: "Solicitar deposito",
    imp_vi_cancelar: "Cancelar lo pedido",
    imp_vi_total: "Total",
    imp_vi_depositado: "depositado",
    imp_vi_con_finanzas: "con finanzas",
    imp_vi_por_solicitar: "por solicitar",
    imp_vi_pedido: "Deposito solicitado a finanzas",
    imp_vi_por_asignar: "Por asignar",
    imp_vi_asignado: "Listo para solicitar",
    imp_vi_solicitado: "Con finanzas",
    imp_vi_ya_depositado: "Depositado",
    imp_mes_siguiente: "Abrir el mes siguiente",
    imp_mes_abierto: "abierto con la misma plantilla",
    imp_mes_tope: "El mes que sigue ya esta abierto",
    col_titular: "Titular",
    col_unidad: "Unidad",
    col_ultimo_mes: "Ultimo mes",
    nav_central: "Monitoreo",
    nav_finanzas: "Gastos",
    nav_nomina: "Nomina",
    nav_personal: "Personal",
    sin_acceso: "Tu rol no tiene acceso a esta pantalla.",

    /* Central de inteligencia y panorama */
    central_titulo: "Central de inteligencia",
    central_sub: "Se actualiza sola cada {s} segundos.",
    cen_sub: "Se actualiza sola cada {s} segundos. Lo urgente, arriba.",
    sc_titulo: "Dias sin cerrar",
    sc_sub: "Dias que ya pasaron y siguen abiertos. Mientras lo esten, esa gente no entra al corte de nomina.",
    sc_cuantos: "{n} pendientes",
    sc_dias: "{n} dias abierto",
    sc_horas: "{n} horas abierto",
    sc_sin_gente: "Sin personal asignado",
    sc_arranco: "Arranco, no cerro",
    sc_sin_marcas: "Sin ninguna marca",
    sc_cerrar: "Cerrar a mano",
    sc_cancelar: "Cancelar",
    sc_inicio: "Hora de inicio",
    sc_fin: "Hora de termino",
    sc_motivo: "Por que se cierra a mano",
    sc_motivo_ejemplo: "Ej: el equipo se quedo sin bateria; confirmado por telefono con el coordinador a las 19:40.",
    sc_falta_motivo: "Escribe al menos 10 caracteres. Dentro de tres meses esta nota va a ser lo unico que explique por que este dia no tiene marcas.",
    sc_advertencia: "Esto queda firmado con tu nombre y la hora. El dia entra al corte de nomina y se marca como cerrado a mano.",
    sc_firmar: "Firmar y cerrar el dia",
    sc_cerrado: "Dia cerrado: {h} horas para {n} personas. Ya entra al corte.",
    cen_roto: "Atender ahora",
    cen_panico: "Alerta de panico",
    cen_callado: "Sin reportar",
    cen_vencido: "Manana sin resolver",
    cen_extra: "Por entrar en horas extra",
    cen_manana: "Manana · el meet and greet",
    cen_manana_sub: "La hora es a la que el equipo tiene que estar parado en "
                    + "el punto, no la del servicio.",
    cen_manana_nada: "Manana no arranca ningun servicio.",
    cen_listos: "listos",
    cen_incompletos: "incompletos",
    cen_corte: "Corte de la vispera",
    cen_antes_del_corte: "Lo que falta todavia es trabajo del dia.",
    cen_paso_el_corte: "Paso el corte: lo que falta hay que resolverlo esta noche.",
    cen_equipo_llega: "El equipo llega",
    cen_servicio_inicia: "Servicio",
    cen_contra_vuelo: "contra vuelo",
    cen_falta_uno: "falta 1 cosa",
    cen_faltan: "faltan {n} cosas",
    cen_todo_listo: "Todo listo",
    cen_ver_servicio: "Abrir el servicio",
    cen_pulso: "En curso",
    cen_pulso_sub: "Lo unico que la central no puede adivinar es cuanto lleva "
                   + "callado cada uno.",
    cen_pulso_nada: "No hay servicios en curso.",
    cen_implantados: "Implantados en curso",
    cen_callado_min: "{n} min sin reportar",
    cen_nunca_reporto: "Todavia no reporta",
    cen_ultimo: "Ultimo",
    cen_semana: "Los proximos dias",
    cen_semana_sub: "Para ver venir el lunes de seis servicios.",
    cen_sin_servicios: "sin servicios",
    cen_dia_completos: "{c} de {t} completos",
    cen_hito_llegada_origen: "Llego al punto",
    cen_hito_contacto_ejecutivo: "Contacto con el ejecutivo",
    cen_hito_llegada_destino: "Llego al destino",
    cen_hito_salida_ruta: "En ruta",
    cen_hito_standby: "En espera",
    cen_hito_fin_servicio: "Fin del servicio",
    cen_p_punto_de_encuentro: "Punto de encuentro",
    cen_p_personal: "Personal",
    cen_p_rol: "Rol de cada quien",
    cen_p_confirmacion: "Confirmacion del equipo",
    cen_p_unidad: "Unidad",
    cen_p_hoja: "Hoja liberada",
    cen_p_vuelo: "Vuelo",
    cen_p_hora: "Hora confirmada",
    cen_p_viaticos: "Viaticos depositados",
    cen_p_hospitales: "Hospitales de la ciudad",
    central_alertas: "Alertas de incidencia",
    central_sin_alertas: "Sin alertas abiertas.",
    canal_boton_app: "Boton de panico (app)",
    canal_boton_vehiculo: "Boton del vehiculo",
    canal_llamada: "Llamada",
    central_tomar: "Tomar",
    central_tomar_equipo: "Tomar y mandar equipo de respuesta",
    central_alerta_tomada: "Alerta tomada",
    central_alerta_tomada_equipo: "Alerta tomada, equipo de respuesta en camino "
      + "Alerta tomada, equipo de respuesta en camino",
    central_alerta_cerrada: "Alerta cerrada",
    central_resolucion_ph: "Que paso y como se resolvio",
    central_falta_resolucion: "Escribe la resolucion",
    central_cerrar: "Cerrar",
    central_equipo_respuesta: "equipo de respuesta",
    central_reportada: "Reportada",
    central_jornada: "jornada",
    central_ver_mapa: "Ver ubicacion en el mapa",
    central_proximos: "Proximos a iniciar",
    central_proximos_sub: "Servicios a menos de dos horas de arrancar. A partir "
      + "de aqui el seguimiento es de la central.",
    central_nada_proximo: "Nada por arrancar en las proximas dos horas.",
    central_listo: "listo",
    central_pendiente: "pendiente",
    col_servicio: "Servicio",
    col_inicia: "Inicia",
    col_estado: "Estado",
    col_equipo: "Equipo",
    col_horario: "Horario",
    col_falta: "Falta",
    col_ultimo_reporte: "Ultimo reporte",
    en_minutos: "en {n} min",
    hace_minutos: "hace {n} min",
    pan_titulo: "Operacion en vivo",
    pan_sub: "Todo lo que esta pasando ahora mismo. Se actualiza "
      + "cada {s} segundos.",
    pan_requiere_atencion: "requiere atencion",
    pan_alertas_sin_tomar: "Alertas de incidencia sin tomar",
    pan_alerta: "alerta",
    pan_alertas: "alertas",
    pan_esperando_central: "esperando a la central",
    pan_cada_una: "Cada una tiene a alguien del otro lado.",
    pan_en_curso: "Servicios en curso",
    pan_en_curso_nota: "Con el equipo en la calle ahora",
    pan_por_iniciar: "Por iniciar (2 h)",
    pan_sin_estar_listos: "sin estar listos",
    pan_todos_listos: "Todos listos",
    pan_alertas_atencion: "Alertas en atencion",
    pan_ya_tomadas: "La central ya las tomo",
    pan_arrancan_pronto: "Arrancan pronto y no estan listos",
    pan_en_la_calle: "En la calle ahora",
    pan_sin_reportar: "sin reportar",
    pan_por_horas_extra: "por entrar en horas extra",
    pan_dinero: "Dinero en movimiento",
    pan_viaticos_transferir: "Viaticos por transferir",
    pan_asignaciones: "asignaciones",
    pan_en_comprobacion: "En comprobacion",
    pan_plazo_vencido: "con plazo vencido",
    pan_nomina_semana: "Nomina de la semana",
    pan_corte: "corte",
    pan_comprobacion_vencida: "Comprobacion vencida",
    pan_vencio: "vencio",
    pan_ajustes: "ajustes entran al proximo corte",
    pan_neto: "neto",
    pan_camino_cobro: "Camino al cobro",
    pan_cierres_abiertos: "Cierres abiertos",
    pan_esperando_finanzas: "Esperando finanzas",
    pan_devueltos: "Devueltos a operacion",
    pan_con_plazo_vencido: "Con plazo vencido",
    pan_regresados: "Regresados por finanzas",
    pan_sin_motivo: "sin motivo",
    pan_esperando_decision: "Esperando una decision",
    pan_malas_calificaciones: "Malas calificaciones sin revisar",
    pan_servicio: "servicio",
    pan_de_5: "de 5",
    pan_incidencias_sin_vb: "Incidencias sin visto bueno del director",
    no_existe: "Esa pantalla no existe.",
    idioma_puesto: "Consola en espanol",

    /* --- cartera */
    cartera_titulo: "Servicios",
    cartera_sub: "Tu cartera y la de los consultores que estes cubriendo.",
    nuevo_servicio: "Nuevo servicio",
    col_folio: "Folio",
    col_cliente: "Cliente",
    col_ejecutivo: "Ejecutivo",
    col_tipo: "Tipo",
    col_estatus: "Estatus",
    col_equipos: "Equipos",

    /* --- personal */
    personal_titulo: "Personal de seguridad",
    personal_sub: "Calificacion de profesionalismo. La confianza avisa cuando "
                + "hay pocas jornadas evaluadas.",
    col_persona: "Persona",
    col_calificacion: "Calificacion",
    col_confianza: "Confianza",
    col_experiencia: "Experiencia",

    /* --- el TS */
    ts_titulo: "TS",
    ts_al_dia: "Cada descarga trae lo ultimo capturado: si movieron una "
             + "parada hace un rato, el PDF ya la trae.",
    ts_sin_liberar: "Se libera al confirmar la asignacion.",
    ts_pdf: "TS en PDF",
    ts_ver: "Solo ver",
    confirmar_ts: "Confirmar asignacion y liberar el TS",
    confirmar_nota: "Revisa que el servicio tenga todo y libera el TS. Es la "
                  + "puerta: antes de eso la hoja seria un borrador.",
    confirmada_el: "Asignacion confirmada el",
    ts_liberado: "El TS esta liberado: descargalo y mandalo por correo.",

    /* --- alta de servicio */
    alta_titulo: "Nuevo servicio",
    alta_sub: "Con el minimo capturado el servicio queda planeado. El equipo, "
            + "la unidad y los viaticos son el paso siguiente.",
    para_planeado: "Para quedar planeado",
    sin_servicios: "Todavia no hay servicios dados de alta.",
    sin_ejecutivo: "Sin ejecutivo",

    min_cliente: "Cliente",
    min_ciudad: "Ciudad de cada equipo",
    min_solicitante: "Quien solicita",
    min_ejecutivo: "Ejecutivo principal de cada equipo",
    min_dia: "Dia y hora de inicio de cada equipo",
    min_inicio: "Punto de inicio de cada equipo",
    falta_info: "Falta informacion",
    dar_de_alta: "Dar de alta",
    cancelar: "Cancelar",
    falta: "Falta",
    queda_planeado: "Con esto el servicio queda planeado. Pasa a asignado "
                  + "cuando tenga equipo y unidad en todos sus dias.",

    cliente: "Cliente",
    elige_cliente: "Selecciona un cliente",
    tipo: "Tipo",
    eventual: "Eventual",
    implantado: "Implantado",
    consultor_asignado: "Consultor asignado",
    pais: "Pais",
    ciudad_opera: "Ciudad donde opera",
    otra_ciudad: "Otra ciudad…",
    nombre_ciudad: "Nombre de la ciudad",
    agregar: "Agregar",
    escribe_ciudad: "Escribe el nombre de la ciudad",
    ciudad_dada_alta: "queda dada de alta",

    quien_solicita: "Quien solicita",
    elegir_solicitante: "Elegir de los que ya piden servicios de este cliente",
    nuevo_solicitante: "Nuevo solicitante",
    nuevo_solicitante_vacio: "Nuevo solicitante — este cliente no tiene ninguno",
    ya_registrado: "ya esta registrado",
    correo_campo: "Correo",
    nombre: "Nombre",
    apellido: "Apellido",
    telefono: "Telefono",

    equipos_titulo: "Equipos del servicio",
    equipos_sub: "Cada equipo va ligado a un ejecutivo principal y lleva sus "
               + "propios dias, su punto de inicio y su task sheet. Alfa, "
               + "Beta, Gamma: el alias lo pone el sistema por orden.",
    agregar_equipo: "Agregar equipo",
    quitar_equipo: "Quitar equipo",
    equipo: "Equipo",
    un_equipo_minimo: "El servicio necesita al menos un equipo",
    ejecutivo_principal: "Ejecutivo principal",
    ejecutivo_sub: "A quien cuida este equipo. Nombre y apellido hacen falta "
                 + "desde el alta; el correo y el telefono se pueden completar "
                 + "despues, sirven para avisarle cuando el equipo este en el "
                 + "punto.",
    mismo_ejecutivo: "El mismo ejecutivo principal del equipo Alfa",

    inicio_y_dias: "Inicio y dias del equipo",
    inicio_y_dias_sub: "Donde arranca el dia 1 y los dias que cubre el equipo. "
                     + "Escribe el hotel, la terminal o la direccion y elige de "
                     + "la lista: de ahi salen la geocerca del conductor y los "
                     + "hospitales del task sheet.",
    direccion_encuentro: "Direccion del punto de encuentro",
    es_aeropuerto: "El punto de encuentro es un aeropuerto",
    vuelo_llegada: "Vuelo de llegada del ejecutivo principal",
    vuelo_llegada_sub: "El equipo llega 45 minutos antes de que aterrice.",
    aerolinea: "Aerolinea",
    numero_vuelo: "Numero de vuelo",
    procedencia: "Procedencia",
    fecha_hora_llegada: "Fecha y hora de llegada",
    llega_antes: "El equipo llega antes",
    en_el_punto: "en el punto de encuentro",
    antes_vuelo: "min antes de que aterrice el vuelo",
    antes_presentacion: "min antes de la hora de presentacion",
    es_aeropuerto_aviso: "Es un aeropuerto: captura el vuelo de llegada",

    dias: "Dias",
    dias_sub: "La modalidad es de cada dia, no del servicio completo: el dia 1 "
            + "puede ser transfer y los siguientes dia completo. La hora de "
            + "presentacion es la del dia 1; los demas dias arrancan con su "
            + "agenda.",
    dia_uno: "Dia 1 · inicio",
    dia_n: "Dia",
    fecha_col: "Fecha",
    modalidad: "Modalidad",
    presentacion: "Presentacion",
    quitar: "Quitar",
    agregar_dia: "Agregar dia",
    un_dia_minimo: "El equipo necesita al menos un dia",
    dia_con_fecha: "Cada equipo necesita al menos un dia con fecha",
    agenda: "Agenda",
    cerrar_agenda: "Cerrar agenda",
    agenda_opcional: "La agenda es opcional: hay clientes que no la comparten "
                   + "y el servicio se va desarrollando sobre la marcha.",
    resumen_dia: "Resumen del dia",
    puntos_renglon: "Puntos, uno por renglon",

    ajustar_pin: "Ajustar el pin y el radio de la geocerca",
    ajustar_pin_sub: "El pin es el del punto de encuentro y se llena solo al "
                   + "elegirlo en el mapa. El radio es el circulo alrededor de "
                   + "ese mismo pin que el conductor tiene que pisar para "
                   + "marcar su llegada.",
    latitud: "Latitud",
    longitud: "Longitud",
    radio_metros: "Radio en metros",
    buscar_para_pin: "Busca la direccion para fijar el punto y su geocerca.",
    buscando_punto: "Buscando el punto…",
    abrir_google: "Abrir en Google Maps",
    sin_google: "La busqueda en Google no esta configurada. Escribe la "
              + "direccion y fija el pin a mano en el apartado de abajo.",
    pendiente_direccion: "Queda pendiente la direccion del punto de encuentro: "
                       + "sin ella no se puede publicar el task sheet.",
    pendiente_pin: "Queda pendiente fijar el punto en el mapa: sin sus "
                 + "coordenadas no hay geocerca ni hospitales cercanos.",
    servicio_planeado: "planeado",
    servicio_borrador: "en borrador",
    mod_full_day: "Dia completo",
    mod_medio_dia: "Medio dia",
    mod_transfer: "Transfer",
    ph_direccion: "Hotel, terminal o direccion. Ej: Las Alcobas Polanco",
    agenda_cargada: " cargada",
    hora: "Hora",
    lugar_direccion: "Lugar y direccion",
    agregar_parada: "Agregar parada",
    ph_parada: "Oficinas corporativas, Reforma 250 piso 12",
    buscar_hotel: "Buscar el hotel en Google",
  },

  en: {
    linea: "Executive Protection",
    correo: "Email",
    contrasena: "Password",
    entrar: "Sign in",
    salir: "Sign out",
    nav_operacion: "Operations",
    nav_eventuales: "EP eventual",
    nav_implantados: "EP implantado",
    implantados_titulo: "Embedded services",
    implantados_sub: "Ongoing: one row per service, not per month.",
    sin_implantados: "No embedded services yet.",
    nuevo_implantado: "New embedded service",
    imp_alta_titulo: "New embedded service",
    imp_alta_sub: "Captured once: the agreement stays, each month opens on its own.",
    imp_trato: "The agreement",
    imp_trato_sub: "What does not change month to month. The task sheet comes from here.",
    imp_punto_fijo: "Fixed point (meet and greet)",
    imp_lat: "Latitude",
    imp_lon: "Longitude",
    imp_geocerca: "Geofence (m)",
    imp_dias_semana: "Days of the week",
    imp_dias_lv: "Monday to Friday",
    imp_dias_ej: "E.g. Monday to Friday",
    imp_hora: "Report time",
    imp_zona: "Operating area",
    imp_zona_buscar: "Search",
    imp_zona_generico: "districts and areas",
    imp_zona_a_mano: "Google did not answer. Type the area and it is taken as is.",
    imp_ciudad_a_mano: "Google did not answer. Try again in a moment.",
    buscar_ciudad: "Search the city on Google",
    ciudad_sin_google: "Google did not answer. Try again in a moment.",
    imp_zona_ej: "E.g. metro area only, no highway",
    imp_cubre: "Agreements",
    imp_cubre_ej: "What was agreed with the client: hours, breaks, who approves changes.",
    imp_no_cubre: "Scope of service",
    imp_no_cubre_ej: "How far the service goes and what is left out.",
    imp_reporta: "Service coordination",
    imp_protocolo: "Service-specific protocol",
    imp_protocolo_ej:
      "How and when the driver reports in, and through which channel: group "
      + "chat, call to the assistant, message to corporate security.\n"
      + "Who may change the route or the schedule on the fly.\n"
      + "What to do if the executive does not come down or cancels without "
      + "notice: how long to wait and who to call.\n"
      + "House rules: whether the driver parks inside or waits outside, "
      + "whether he may leave the vehicle, whether the gate needs pre-registration.\n"
      + "On an incident: who gets told first, whether the client wants to know "
      + "before the control room.",
    imp_mes: "First month",
    imp_asignacion: "Assignment and coordination",
    imp_volver: "Back to the list",
    imp_no_existe: "That service does not exist or is not embedded.",
    imp_abrir_mes: "Open the first month",
    imp_cargando: "One moment...",
    imp_liberar: "Release the sheet",
    imp_liberada: "sheet released, version",
    imp_ts_nota: "The sheet is built from the latest data: each button "
      + "generates it again.",
    imp_ventana_bloqueada: "The browser blocked the sheet window.",
    imp_sin_gente_ciudad: "No security staff registered in that city. Add "
      + "them under Staff, or change the city of the service.",
    imp_sin_flota_ciudad: "No vehicles in that city.",
    imp_col_posicion: "Position",
    imp_col_cubre: "Covered by",
    imp_del_equipo: "on the team",
    imp_ocupado: "busy that day",
    imp_abrir_dia: "Open the day",
    imp_cubrir_dia: "Save who covers it",
    imp_cerrar_dia: "Close the day",
    imp_dia_guardado: "Day covered.",
    imp_dia_cerrado: "Day closed.",
    imp_todo_el_fin: "Cover also",
    imp_sin_plantilla: "The month has no roster.",
    imp_editar: "Edit",
    imp_guardar: "Save changes",
    imp_acuerdo_corregido: "Agreement updated.",
    imp_sin_arranque: "This service has no start date. Set it here to open "
      + "the month.",
    imp_arranque_guardado: "Start date saved.",
    imp_por_cubrir_aviso: "days this month with nobody covering them",
    imp_bloqueo_asignacion: "Client and agreement come first. Missing:",
    imp_cobro: "How the month is billed",
    imp_guardar_acuerdo: "Save client and agreement",
    imp_acuerdo_guardado: "saved. It has a folio now; the assignment can be "
      + "finished later.",
    imp_mes_sub: "The cut-off is the last day of the month; the next one starts on the 1st.",
    imp_anio: "Year",
    imp_fecha_inicio: "Service start date",
    imp_dias_servicio: "Days of service",
    imp_lunes_viernes: "Monday to Friday",
    imp_lunes_sabado: "Monday to Saturday",
    imp_todos_los_dias: "Every day",
    imp_calendario: "The month",
    imp_sin_fecha: "Set the start date to see the month.",
    imp_dia_cubierto: "Covered by the service team",
    imp_dia_por_cubrir: "Contracted: still needs someone",
    imp_dia_sin_servicio: "No service contracted",
    imp_dia_antes: "Before the service starts",
    imp_dia_abierto: "Opened by hand: the same team covers it",
    imp_dia_se_puede_abrir: "Not contracted. Click to open it with the same team",
    imp_calendario_ayuda: "The calendar follows the days of service agreed "
      + "above. Contracted weekends stay amber until someone is named, and "
      + "that happens in the month panel, once the service is running.",
    imp_leyenda_verde: "Covered",
    imp_leyenda_ambar: "Needs someone",
    imp_leyenda_gris: "No service",
    imp_falta_fecha: "Date the service starts",
    imp_mes_campo: "Month",
    imp_desde_dia: "Starts on day",
    imp_desde_ej: "Empty: full month",
    imp_modalidad: "Shift",
    imp_sin_modalidad: "This country has no full day in the catalogue",
    imp_esquema: "How it is billed",
    imp_por_dia: "Per day worked",
    imp_mes_completo: "One price for the month",
    imp_fines_de_semana: "Includes weekends",
    imp_precio_mes_vehiculo: "Vehicle per month",
    imp_precio_dia_personal: "Staff per day",
    imp_precio_dia_adicional: "Extra day",
    imp_precio_mes_completo: "Monthly price",
    imp_plantilla: "This month's roster",
    imp_plantilla_sub: "Any mix, with two rules: at least one security person, "
      + "and every vehicle with one aboard.",
    imp_elige_persona: "Choose who goes",
    imp_col_persona: "Security staff",
    imp_col_categoria_persona: "Category",
    imp_elige_categoria_persona: "Category first",
    imp_col_categoria: "Vehicle category",
    imp_elige_categoria: "Category first",
    imp_elige_unidad: "Choose the vehicle",
    imp_libre: "free",
    imp_sin_unidad: "No vehicle",
    imp_agregar_persona: "Add person",
    imp_agregar_unidad: "Add vehicle",
    imp_unidades: "Vehicles",
    imp_col_lleva: "Driven by",
    imp_elige_conductor: "Choose who drives it",
    imp_falta: "Missing before it can be created",
    imp_falta_modalidad: "Service shift",
    imp_falta_punto: "Fixed reporting point",
    imp_falta_plantilla: "At least one person on the roster",
    imp_dar_alta: "Create embedded service",
    imp_dias_armados: "days set up",
    imp_meses_abiertos: "Open months",
    imp_sin_meses: "This service has no month open yet",
    imp_viaticos: "Per diem this month",
    imp_taller: "Vehicle to the shop",
    imp_hospitales: "Reference hospitals",
    imp_tabulador: "Per diem table",
    imp_elige_rol: "Pick the role…",
    imp_col_rol: "Role",
    imp_rol_sub: "The role belongs to the task. Security staff is general: the "
                 + "same agent who drives today coordinates tomorrow, and the "
                 + "role sets what is charged and what is paid.",
    imp_tab_sub: "What was agreed with this client, per day and per person. "
                 + "Embedded services are negotiated one by one, so this "
                 + "table belongs to this agreement and no other.",
    imp_tab_concepto: "Item",
    imp_tab_monto: "Per day",
    imp_tab_abierto: "Open amount",
    imp_tab_abierto_ayuda: "It exists, but the amount is entered on the day",
    imp_tab_nota: "Note",
    imp_tab_va: "On",
    imp_tab_sugerido: "company suggests",
    imp_tab_total: "Total per day and per person",
    imp_tab_guardar: "Save the table",
    imp_tab_guardado: "Table saved",
    imp_tab_vacio: "This agreement has no per diem table yet. Without it, the "
                   + "monthly proposal comes out at zero.",
    imp_tab_alimentos: "Meals",
    imp_tab_traslado: "Staff transport",
    imp_tab_combustible: "Fuel",
    imp_tab_casetas: "Tolls",
    imp_tab_hospedaje: "Lodging",
    imp_tab_otros: "Other",
    imp_hospitales_sub: "The three closest to the service point, in its city. "
                        + "This is what the team reads in an emergency.",
    imp_hosp_vacio: "This city has no hospitals on file. The sheet would go "
                    + "out with no medical reference.",
    imp_hosp_sin_punto: "Without the service point they cannot be searched.",
    imp_hosp_buscar: "Search nearby on Google",
    imp_hosp_nivel: "Level of care",
    imp_hosp_primero: "First level (stabilizes and refers)",
    imp_hosp_segundo: "Second level",
    imp_hosp_tercero: "Third level (operating room)",
    imp_hosp_agregar: "Add to the catalog",
    imp_hosp_ya: "Already on file",
    imp_hosp_falta_nivel: "Set the level. Google does not know it and it is "
                          + "not guessed.",
    imp_hosp_agregado: "is now on the city catalog",
    imp_hosp_nota: "Google fills in the name, address, phone and coordinates. "
                   + "Centauro sets the level once: that is where the "
                   + "operating-room rule comes from.",
    imp_taller_sub: "The vehicle goes out of service and another takes its "
                    + "place on the days in range. The block applies company "
                    + "wide, not only to this service.",
    imp_taller_sale: "Vehicle going out",
    imp_taller_entra: "Vehicle coming in",
    imp_taller_desde: "From",
    imp_taller_hasta: "Until (optional)",
    imp_taller_tipo: "Reason",
    imp_taller_preventivo: "Preventive maintenance",
    imp_taller_correctivo: "Corrective maintenance",
    imp_taller_donde: "Shop",
    imp_taller_folio: "Work order",
    imp_taller_nota: "Note",
    imp_taller_guardar: "Send to the shop",
    imp_taller_libre: "free",
    imp_taller_de: "of",
    imp_taller_hecho: "is out of service; covered by",
    imp_taller_fuera: "Out of service today",
    imp_taller_sin_fecha: "no return date",
    imp_taller_abrir: "Send a vehicle to the shop",
    imp_taller_cerrar: "Close",
    imp_taller_falta: "Say which vehicle comes in",
    imp_viaticos_sub: "One deposit per person, for their days this month. "
                      + "The system proposes from the table; you decide the "
                      + "amount. It closes monthly.",
    imp_vi_persona: "Person",
    imp_vi_propone: "System proposes",
    imp_vi_deposita: "Deposit",
    imp_vi_mas: "Deposit more",
    imp_vi_estado: "Status",
    imp_vi_dias: "days",
    imp_vi_guardar: "Save",
    imp_vi_solicitar: "Request deposit",
    imp_vi_cancelar: "Cancel request",
    imp_vi_total: "Total",
    imp_vi_depositado: "deposited",
    imp_vi_con_finanzas: "with finance",
    imp_vi_por_solicitar: "to request",
    imp_vi_pedido: "Deposit requested from finance",
    imp_vi_por_asignar: "Not set",
    imp_vi_asignado: "Ready to request",
    imp_vi_solicitado: "With finance",
    imp_vi_ya_depositado: "Deposited",
    imp_mes_siguiente: "Open next month",
    imp_mes_abierto: "opened with the same team",
    imp_mes_tope: "Next month is already open",
    col_titular: "Assigned",
    col_unidad: "Vehicle",
    col_ultimo_mes: "Last month",
    nav_central: "Monitoring",
    nav_finanzas: "Expenses",
    nav_nomina: "Payroll",
    nav_personal: "Staff",
    sin_acceso: "Your role has no access to this screen.",

    /* Central de inteligencia y panorama */
    central_titulo: "Control room",
    central_sub: "Refreshes on its own every {s} seconds.",
    cen_sub: "Refreshes on its own every {s} seconds. Urgent things on top.",
    sc_titulo: "Days still open",
    sc_sub: "Days that already happened and are still open. Until they close, that crew does not make it into payroll.",
    sc_cuantos: "{n} pending",
    sc_dias: "open {n} days",
    sc_horas: "open {n} hours",
    sc_sin_gente: "No crew assigned",
    sc_arranco: "Started, never closed",
    sc_sin_marcas: "No check-ins at all",
    sc_cerrar: "Close by hand",
    sc_cancelar: "Cancel",
    sc_inicio: "Start time",
    sc_fin: "End time",
    sc_motivo: "Why it is being closed by hand",
    sc_motivo_ejemplo: "E.g.: the crew ran out of battery; confirmed by phone with the coordinator at 19:40.",
    sc_falta_motivo: "Write at least 10 characters. Three months from now this note will be the only thing explaining why this day has no check-ins.",
    sc_advertencia: "This is signed with your name and the time. The day enters payroll and is flagged as closed by hand.",
    sc_firmar: "Sign and close the day",
    sc_cerrado: "Day closed: {h} hours for {n} people. It now enters payroll.",
    cen_roto: "Attend now",
    cen_panico: "Panic alert",
    cen_callado: "Not reporting",
    cen_vencido: "Tomorrow unresolved",
    cen_extra: "About to go into overtime",
    cen_manana: "Tomorrow · the meet and greet",
    cen_manana_sub: "The time shown is when the team must be standing at the "
                    + "meeting point, not when the service starts.",
    cen_manana_nada: "No service starts tomorrow.",
    cen_listos: "ready",
    cen_incompletos: "incomplete",
    cen_corte: "Eve cut-off",
    cen_antes_del_corte: "What is missing is still today's work.",
    cen_paso_el_corte: "Past the cut-off: what is missing has to be solved tonight.",
    cen_equipo_llega: "Team arrives",
    cen_servicio_inicia: "Service",
    cen_contra_vuelo: "against flight",
    cen_falta_uno: "1 thing missing",
    cen_faltan: "{n} things missing",
    cen_todo_listo: "All set",
    cen_ver_servicio: "Open the service",
    cen_pulso: "In progress",
    cen_pulso_sub: "The one thing the control room cannot guess is how long "
                   + "each one has been silent.",
    cen_pulso_nada: "No services in progress.",
    cen_implantados: "Embedded services in progress",
    cen_callado_min: "{n} min without reporting",
    cen_nunca_reporto: "Has not reported yet",
    cen_ultimo: "Last",
    cen_semana: "The next few days",
    cen_semana_sub: "To see the six-service Monday coming.",
    cen_sin_servicios: "no services",
    cen_dia_completos: "{c} of {t} complete",
    cen_hito_llegada_origen: "At the meeting point",
    cen_hito_contacto_ejecutivo: "Contact with the principal",
    cen_hito_llegada_destino: "Arrived at destination",
    cen_hito_salida_ruta: "On route",
    cen_hito_standby: "Standing by",
    cen_hito_fin_servicio: "Service ended",
    cen_p_punto_de_encuentro: "Meeting point",
    cen_p_personal: "Personnel",
    cen_p_rol: "Role for each",
    cen_p_confirmacion: "Team confirmation",
    cen_p_unidad: "Vehicle",
    cen_p_hoja: "Sheet released",
    cen_p_vuelo: "Flight",
    cen_p_hora: "Time confirmed",
    cen_p_viaticos: "Per diem deposited",
    cen_p_hospitales: "Hospitals for the city",
    central_alertas: "Incident alerts",
    central_sin_alertas: "No open alerts.",
    canal_boton_app: "Panic button (app)",
    canal_boton_vehiculo: "Vehicle button",
    canal_llamada: "Phone call",
    central_tomar: "Take it",
    central_tomar_equipo: "Take it and send a response team",
    central_alerta_tomada: "Alert taken",
    central_alerta_tomada_equipo: "Alert taken, response team on the way",
    central_alerta_cerrada: "Alert closed",
    central_resolucion_ph: "What happened and how it was resolved",
    central_falta_resolucion: "Write how it was resolved",
    central_cerrar: "Close",
    central_equipo_respuesta: "response team",
    central_reportada: "Reported",
    central_jornada: "day",
    central_ver_mapa: "See the location on the map",
    central_proximos: "Starting soon",
    central_proximos_sub: "Services less than two hours from starting. From "
      + "here on, the control room follows them.",
    central_nada_proximo: "Nothing starting in the next two hours.",
    central_listo: "ready",
    central_pendiente: "pending",
    col_servicio: "Service",
    col_inicia: "Starts",
    col_estado: "Status",
    col_equipo: "Team",
    col_horario: "Hours",
    col_falta: "Missing",
    col_ultimo_reporte: "Last report",
    en_minutos: "in {n} min",
    hace_minutos: "{n} min ago",
    pan_titulo: "Live operation",
    pan_sub: "Everything happening right now. Refreshes every {s} seconds.",
    pan_requiere_atencion: "needs attention",
    pan_alertas_sin_tomar: "Incident alerts nobody has taken",
    pan_alerta: "alert",
    pan_alertas: "alerts",
    pan_esperando_central: "waiting for the control room",
    pan_cada_una: "Each one has someone on the other end.",
    pan_en_curso: "Services running",
    pan_en_curso_nota: "With the team on the street right now",
    pan_por_iniciar: "Starting within 2 h",
    pan_sin_estar_listos: "not ready",
    pan_todos_listos: "All ready",
    pan_alertas_atencion: "Alerts being handled",
    pan_ya_tomadas: "The control room already took them",
    pan_arrancan_pronto: "Starting soon and not ready",
    pan_en_la_calle: "On the street now",
    pan_sin_reportar: "no report yet",
    pan_por_horas_extra: "about to go into overtime",
    pan_dinero: "Money in motion",
    pan_viaticos_transferir: "Per diem to transfer",
    pan_asignaciones: "assignments",
    pan_en_comprobacion: "Being documented",
    pan_plazo_vencido: "past due",
    pan_nomina_semana: "This week's payroll",
    pan_corte: "cutoff",
    pan_comprobacion_vencida: "Documentation past due",
    pan_vencio: "due",
    pan_ajustes: "adjustments go into the next cutoff",
    pan_neto: "net",
    pan_camino_cobro: "On the way to billing",
    pan_cierres_abiertos: "Open closings",
    pan_esperando_finanzas: "Waiting on finance",
    pan_devueltos: "Returned to operations",
    pan_con_plazo_vencido: "Past due",
    pan_regresados: "Sent back by finance",
    pan_sin_motivo: "no reason given",
    pan_esperando_decision: "Waiting on a decision",
    pan_malas_calificaciones: "Bad ratings nobody has reviewed",
    pan_servicio: "service",
    pan_de_5: "out of 5",
    pan_incidencias_sin_vb: "Incidents without the director's sign-off",
    no_existe: "That screen does not exist.",
    idioma_puesto: "Console in English",

    cartera_titulo: "Services",
    cartera_sub: "Your portfolio and that of the consultants you are covering.",
    nuevo_servicio: "New service",
    col_folio: "Number",
    col_cliente: "Client",
    col_ejecutivo: "Principal",
    col_tipo: "Type",
    col_estatus: "Status",
    col_equipos: "Teams",

    personal_titulo: "Security staff",
    personal_sub: "Professionalism rating. Confidence flags the people with "
                + "few rated days.",
    col_persona: "Person",
    col_calificacion: "Rating",
    col_confianza: "Confidence",
    col_experiencia: "Experience",

    ts_titulo: "TS",
    ts_al_dia: "Every download carries the latest: if a stop moved an hour "
             + "ago, the PDF already has it.",
    ts_sin_liberar: "Released when the assignment is confirmed.",
    ts_pdf: "TS as PDF",
    ts_ver: "View only",
    confirmar_ts: "Confirm assignment and release the TS",
    confirmar_nota: "Check that the service has everything and release the "
                  + "TS. Before that, the sheet would be a draft.",
    confirmada_el: "Assignment confirmed on",
    ts_liberado: "The TS is released: download it and send it by email.",

    alta_titulo: "New service",
    alta_sub: "With the minimum captured the service is planned. Team, vehicle "
            + "and per diems come next.",
    para_planeado: "To be planned",
    sin_servicios: "No services yet.",
    sin_ejecutivo: "No principal",

    min_cliente: "Client",
    min_ciudad: "City of each team",
    min_solicitante: "Requested by",
    min_ejecutivo: "Principal of each team",
    min_dia: "Date and start time of each team",
    min_inicio: "Starting point of each team",
    falta_info: "Missing information",
    dar_de_alta: "Create service",
    cancelar: "Cancel",
    falta: "Missing",
    queda_planeado: "With this the service is planned. It becomes assigned "
                  + "once every day has a team and a vehicle.",

    cliente: "Client",
    elige_cliente: "Select a client",
    tipo: "Type",
    eventual: "One-off",
    implantado: "Embedded",
    consultor_asignado: "Assigned consultant",
    pais: "Country",
    ciudad_opera: "City it operates in",
    otra_ciudad: "Another city…",
    nombre_ciudad: "City name",
    agregar: "Add",
    escribe_ciudad: "Type the city name",
    ciudad_dada_alta: "has been added",

    quien_solicita: "Requested by",
    elegir_solicitante: "Pick from the people who already request services for "
                      + "this client",
    nuevo_solicitante: "New requester",
    nuevo_solicitante_vacio: "New requester — this client has none yet",
    ya_registrado: "is already registered",
    correo_campo: "Email",
    nombre: "First name",
    apellido: "Last name",
    telefono: "Phone",

    equipos_titulo: "Teams on this service",
    equipos_sub: "Each team is tied to a principal and carries its own days, "
               + "starting point and task sheet. Alfa, Beta, Gamma: the system "
               + "names them in order.",
    agregar_equipo: "Add team",
    quitar_equipo: "Remove team",
    equipo: "Team",
    un_equipo_minimo: "The service needs at least one team",
    ejecutivo_principal: "Principal",
    ejecutivo_sub: "Who this team protects. First and last name are needed "
                 + "from the start; email and phone can come later, they are "
                 + "used to tell them the team is in position.",
    mismo_ejecutivo: "Same principal as team Alfa",

    inicio_y_dias: "Start and days of the team",
    inicio_y_dias_sub: "Where day 1 starts and the days the team covers. Type "
                     + "the hotel, terminal or address and pick it from the "
                     + "list: the driver's geofence and the task sheet "
                     + "hospitals come from there.",
    direccion_encuentro: "Meeting point address",
    es_aeropuerto: "The meeting point is an airport",
    vuelo_llegada: "Principal's inbound flight",
    vuelo_llegada_sub: "The team is in position 45 minutes before landing.",
    aerolinea: "Airline",
    numero_vuelo: "Flight number",
    procedencia: "From",
    fecha_hora_llegada: "Arrival date and time",
    llega_antes: "The team arrives earlier",
    en_el_punto: "at the meeting point",
    antes_vuelo: "min before the flight lands",
    antes_presentacion: "min before the reporting time",
    es_aeropuerto_aviso: "This is an airport: capture the inbound flight",

    dias: "Days",
    dias_sub: "The mode belongs to each day, not to the whole service: day 1 "
            + "can be a transfer and the rest full days. The reporting time is "
            + "day 1's; the other days start with their itinerary.",
    dia_uno: "Day 1 · start",
    dia_n: "Day",
    fecha_col: "Date",
    modalidad: "Mode",
    presentacion: "Reporting",
    quitar: "Remove",
    agregar_dia: "Add day",
    un_dia_minimo: "The team needs at least one day",
    dia_con_fecha: "Every team needs at least one day with a date",
    agenda: "Itinerary",
    cerrar_agenda: "Close itinerary",
    agenda_opcional: "The itinerary is optional: some clients do not share it "
                   + "and the day unfolds as it goes.",
    resumen_dia: "Summary of the day",
    puntos_renglon: "Stops, one per line",

    ajustar_pin: "Adjust the pin and the geofence radius",
    ajustar_pin_sub: "The pin is the meeting point's and fills in when you "
                   + "pick it on the map. The radius is the circle around that "
                   + "pin the driver has to step into to mark arrival.",
    latitud: "Latitude",
    longitud: "Longitude",
    radio_metros: "Radius in metres",
    buscar_para_pin: "Search the address to set the point and its geofence.",
    buscando_punto: "Locating the point…",
    abrir_google: "Open in Google Maps",
    sin_google: "Google search is not configured. Type the address and set the "
              + "pin by hand in the section below.",
    pendiente_direccion: "The meeting point address is still pending: without "
                       + "it the task sheet cannot be published.",
    pendiente_pin: "Setting the pin on the map is still pending: without its "
                 + "coordinates there is no geofence and no nearby hospitals.",
    servicio_planeado: "planned",
    servicio_borrador: "as a draft",
    mod_full_day: "Full day",
    mod_medio_dia: "Half day",
    mod_transfer: "Transfer",
    ph_direccion: "Hotel, terminal or address. E.g. Las Alcobas Polanco",
    agenda_cargada: " loaded",
    hora: "Time",
    lugar_direccion: "Place and address",
    agregar_parada: "Add stop",
    ph_parada: "Corporate offices, Reforma 250 floor 12",
    buscar_hotel: "Search the hotel on Google",
  },

  pt: {
    linea: "Protecao Executiva",
    correo: "E-mail",
    contrasena: "Senha",
    entrar: "Entrar",
    salir: "Sair",
    nav_operacion: "Operacao",
    nav_eventuales: "EP eventual",
    nav_implantados: "EP implantado",
    implantados_titulo: "Servicos implantados",
    implantados_sub: "Continuos: uma linha por servico, nao por mes.",
    sin_implantados: "Ainda nao ha implantados.",
    nuevo_implantado: "Novo implantado",
    imp_alta_titulo: "Novo servico implantado",
    imp_alta_sub: "Capturado uma vez: o acordo nao muda e cada mes abre sozinho.",
    imp_trato: "O acordo",
    imp_trato_sub: "O que nao muda de mes a mes. Daqui sai o task sheet.",
    imp_punto_fijo: "Ponto fixo (meet and greet)",
    imp_lat: "Latitude",
    imp_lon: "Longitude",
    imp_geocerca: "Geocerca (m)",
    imp_dias_semana: "Dias da semana",
    imp_dias_lv: "Segunda a sexta",
    imp_dias_ej: "Ex: segunda a sexta",
    imp_hora: "Hora de apresentacao",
    imp_zona: "Zona de operacao",
    imp_zona_buscar: "Busque",
    imp_zona_generico: "municipios e zonas",
    imp_zona_a_mano: "O Google nao respondeu. Escreva a zona e vai assim mesmo.",
    imp_ciudad_a_mano: "O Google nao respondeu. Tente de novo em um momento.",
    buscar_ciudad: "Busque a cidade no Google",
    ciudad_sin_google: "O Google nao respondeu. Tente de novo em um momento.",
    imp_zona_ej: "Ex: regiao metropolitana, sem estrada",
    imp_cubre: "Acordos",
    imp_cubre_ej: "O que foi acordado com o cliente: horario, descansos, quem autoriza mudancas.",
    imp_no_cubre: "Alcance do servico",
    imp_no_cubre_ej: "Ate onde vai o servico e o que fica de fora.",
    imp_reporta: "Coordenacao do servico",
    imp_protocolo: "Protocolo especial do servico",
    imp_protocolo_ej:
      "Como e a que horas avisa que chegou, e por qual canal: grupo de "
      + "WhatsApp, ligacao para a assistente, mensagem a seguranca corporativa.\n"
      + "Quem pode mudar a rota ou o horario no caminho.\n"
      + "O que fazer se o executivo nao descer na hora ou cancelar sem avisar: "
      + "quanto espera e para quem liga.\n"
      + "Regras da casa do cliente: se entra no estacionamento ou espera fora, "
      + "se pode deixar o veiculo, se ha portaria com registro previo.\n"
      + "Diante de uma ocorrencia: quem e avisado primeiro, se o cliente quer "
      + "saber antes da central.",
    imp_mes: "O primeiro mes",
    imp_asignacion: "Atribuicao e coordenacao",
    imp_volver: "Voltar a carteira",
    imp_no_existe: "Esse servico nao existe ou nao e implantado.",
    imp_abrir_mes: "Abrir o primeiro mes",
    imp_cargando: "Um momento...",
    imp_liberar: "Liberar a folha",
    imp_liberada: "folha liberada, versao",
    imp_ts_nota: "A folha e montada com o ultimo capturado: cada botao a "
      + "gera de novo.",
    imp_ventana_bloqueada: "O navegador bloqueou a janela da folha.",
    imp_sin_gente_ciudad: "Nao ha pessoal de seguranca cadastrado nessa "
      + "cidade. Cadastre em Equipe, ou mude a cidade do servico.",
    imp_sin_flota_ciudad: "Nao ha veiculos nessa cidade.",
    imp_col_posicion: "Posicao do mes",
    imp_col_cubre: "Quem cobre",
    imp_del_equipo: "da equipe",
    imp_ocupado: "ocupado nesse dia",
    imp_abrir_dia: "Abrir o dia",
    imp_cubrir_dia: "Salvar quem cobre",
    imp_cerrar_dia: "Fechar o dia",
    imp_dia_guardado: "Dia coberto.",
    imp_dia_cerrado: "Dia fechado.",
    imp_todo_el_fin: "Cobrir tambem o",
    imp_sin_plantilla: "O mes nao tem equipe.",
    imp_editar: "Editar",
    imp_guardar: "Salvar alteracoes",
    imp_acuerdo_corregido: "Acordo atualizado.",
    imp_sin_arranque: "Este servico nao tem dia de inicio. Coloque aqui para "
      + "poder abrir o mes.",
    imp_arranque_guardado: "Dia de inicio salvo.",
    imp_por_cubrir_aviso: "dias do mes sem quem cubra",
    imp_bloqueo_asignacion: "Primeiro o cliente e o acordo. Falta:",
    imp_cobro: "Como se cobra o mes",
    imp_guardar_acuerdo: "Salvar cliente e acordo",
    imp_acuerdo_guardado: "salvo. Ja tem folio; a atribuicao pode terminar "
      + "depois.",
    imp_mes_sub: "O corte e no ultimo dia do mes; o seguinte comeca no dia 1.",
    imp_anio: "Ano",
    imp_fecha_inicio: "Dia de inicio do servico",
    imp_dias_servicio: "Dias de servico",
    imp_lunes_viernes: "Segunda a sexta",
    imp_lunes_sabado: "Segunda a sabado",
    imp_todos_los_dias: "Todos os dias",
    imp_calendario: "O mes",
    imp_sin_fecha: "Coloque a data de inicio para ver o mes.",
    imp_dia_cubierto: "Coberto pela equipe do servico",
    imp_dia_por_cubrir: "Contratado: falta dizer quem cobre",
    imp_dia_sin_servicio: "Sem servico contratado",
    imp_dia_antes: "Antes de o servico comecar",
    imp_dia_abierto: "Aberto a mao: cobre a mesma equipe",
    imp_dia_se_puede_abrir: "Sem contratar. Clique para abrir com a mesma equipe",
    imp_calendario_ayuda: "O calendario sai dos dias de servico acordados "
      + "acima. Os fins de semana contratados ficam em ambar ate se dizer "
      + "quem cobre, e isso se faz no painel do mes, com o servico ja "
      + "correndo.",
    imp_leyenda_verde: "Coberto",
    imp_leyenda_ambar: "Falta quem cubra",
    imp_leyenda_gris: "Sem servico",
    imp_falta_fecha: "Data em que o servico comeca",
    imp_mes_campo: "Mes",
    imp_desde_dia: "Comeca no dia",
    imp_desde_ej: "Vazio: mes completo",
    imp_modalidad: "Modalidade",
    imp_sin_modalidad: "Este pais nao tem dia completo no catalogo",
    imp_esquema: "Como se cobra",
    imp_por_dia: "Por dia trabalhado",
    imp_mes_completo: "Um preco pelo mes",
    imp_fines_de_semana: "Inclui fins de semana",
    imp_precio_mes_vehiculo: "Veiculo por mes",
    imp_precio_dia_personal: "Pessoal por dia",
    imp_precio_dia_adicional: "Dia adicional",
    imp_precio_mes_completo: "Preco do mes",
    imp_plantilla: "A equipe do mes",
    imp_plantilla_sub: "Qualquer combinacao, com duas regras: pelo menos uma "
      + "pessoa de seguranca, e todo veiculo com a sua.",
    imp_elige_persona: "Escolha quem vai",
    imp_col_persona: "Pessoa de seguranca",
    imp_col_categoria_persona: "Categoria",
    imp_elige_categoria_persona: "Primeiro a categoria",
    imp_col_categoria: "Categoria do veiculo",
    imp_elige_categoria: "Primeiro a categoria",
    imp_elige_unidad: "Escolha o veiculo",
    imp_libre: "livre",
    imp_sin_unidad: "Sem veiculo",
    imp_agregar_persona: "Adicionar pessoa",
    imp_agregar_unidad: "Adicionar veiculo",
    imp_unidades: "Veiculos",
    imp_col_lleva: "Quem dirige",
    imp_elige_conductor: "Escolha quem dirige",
    imp_falta: "Falta para dar entrada",
    imp_falta_modalidad: "Modalidade do servico",
    imp_falta_punto: "Ponto fixo de apresentacao",
    imp_falta_plantilla: "Pelo menos uma pessoa na equipe",
    imp_dar_alta: "Dar entrada no implantado",
    imp_dias_armados: "dias montados",
    imp_meses_abiertos: "Meses abertos",
    imp_sin_meses: "Este servico ainda nao tem nenhum mes aberto",
    imp_viaticos: "Diarias do mes",
    imp_taller: "Unidade na oficina",
    imp_hospitales: "Hospitais de referencia",
    imp_tabulador: "Tabela de diarias",
    imp_elige_rol: "Escolha o papel…",
    imp_col_rol: "Papel",
    imp_rol_sub: "O papel e da tarefa. O pessoal de seguranca e geral: o mesmo "
                 + "agente que hoje dirige amanha coordena, e do papel saem o "
                 + "que se cobra e o que se paga.",
    imp_tab_sub: "O que foi acordado com este cliente, por dia e por pessoa. "
                 + "O implantado se negocia um a um, entao esta tabela e "
                 + "deste acordo e de nenhum outro.",
    imp_tab_concepto: "Item",
    imp_tab_monto: "Por dia",
    imp_tab_abierto: "Valor aberto",
    imp_tab_abierto_ayuda: "Existe, mas o valor se lanca no dia",
    imp_tab_nota: "Nota",
    imp_tab_va: "Vai",
    imp_tab_sugerido: "a empresa sugere",
    imp_tab_total: "Total por dia e por pessoa",
    imp_tab_guardar: "Salvar a tabela",
    imp_tab_guardado: "Tabela salva",
    imp_tab_vacio: "Este acordo ainda nao tem tabela. Sem ela, a proposta de "
                   + "diarias do mes sai em zero.",
    imp_tab_alimentos: "Alimentacao",
    imp_tab_traslado: "Deslocamento do pessoal",
    imp_tab_combustible: "Combustivel",
    imp_tab_casetas: "Pedagios",
    imp_tab_hospedaje: "Hospedagem",
    imp_tab_otros: "Outros",
    imp_hospitales_sub: "Os tres mais proximos do ponto do servico, na sua "
                        + "cidade. E o que a equipe le numa emergencia.",
    imp_hosp_vacio: "Esta cidade nao tem hospitais cadastrados. A folha sairia "
                    + "sem referencia medica.",
    imp_hosp_sin_punto: "Sem o ponto do servico nao da para busca-los.",
    imp_hosp_buscar: "Buscar perto no Google",
    imp_hosp_nivel: "Nivel de atendimento",
    imp_hosp_primero: "Primeiro nivel (estabiliza e encaminha)",
    imp_hosp_segundo: "Segundo nivel",
    imp_hosp_tercero: "Terceiro nivel (centro cirurgico)",
    imp_hosp_agregar: "Adicionar ao catalogo",
    imp_hosp_ya: "Ja esta no catalogo",
    imp_hosp_falta_nivel: "Marque o nivel. O Google nao sabe e nao se adivinha.",
    imp_hosp_agregado: "entrou no catalogo da cidade",
    imp_hosp_nota: "O Google preenche nome, endereco, telefone e coordenadas. "
                   + "O nivel a Centauro marca uma unica vez: dali sai a regra "
                   + "do centro cirurgico.",
    imp_taller_sub: "A unidade sai de circulacao e outra toma o seu lugar "
                    + "nos dias do trecho. O bloqueio vale para toda a "
                    + "empresa, nao so para este servico.",
    imp_taller_sale: "Unidade que sai",
    imp_taller_entra: "Unidade que entra",
    imp_taller_desde: "De",
    imp_taller_hasta: "Ate (opcional)",
    imp_taller_tipo: "Motivo",
    imp_taller_preventivo: "Manutencao preventiva",
    imp_taller_correctivo: "Manutencao corretiva",
    imp_taller_donde: "Oficina",
    imp_taller_folio: "Ordem de servico",
    imp_taller_nota: "Nota",
    imp_taller_guardar: "Enviar para a oficina",
    imp_taller_libre: "livre",
    imp_taller_de: "de",
    imp_taller_hecho: "saiu de circulacao; e coberta por",
    imp_taller_fuera: "Fora de circulacao hoje",
    imp_taller_sin_fecha: "sem data de entrega",
    imp_taller_abrir: "Enviar uma unidade para a oficina",
    imp_taller_cerrar: "Fechar",
    imp_taller_falta: "Diga qual unidade entra",
    imp_viaticos_sub: "Um deposito por pessoa, pelos seus dias deste mes. "
                      + "O sistema propoe pela tabela; o valor voce decide. "
                      + "O fechamento e mensal.",
    imp_vi_persona: "Pessoa",
    imp_vi_propone: "O sistema propoe",
    imp_vi_deposita: "Deposita-se",
    imp_vi_mas: "Deposita-se mais",
    imp_vi_estado: "Estado",
    imp_vi_dias: "dias",
    imp_vi_guardar: "Salvar",
    imp_vi_solicitar: "Solicitar deposito",
    imp_vi_cancelar: "Cancelar o pedido",
    imp_vi_total: "Total",
    imp_vi_depositado: "depositado",
    imp_vi_con_finanzas: "com financeiro",
    imp_vi_por_solicitar: "a solicitar",
    imp_vi_pedido: "Deposito solicitado ao financeiro",
    imp_vi_por_asignar: "A definir",
    imp_vi_asignado: "Pronto para solicitar",
    imp_vi_solicitado: "Com financeiro",
    imp_vi_ya_depositado: "Depositado",
    imp_mes_siguiente: "Abrir o mes seguinte",
    imp_mes_abierto: "aberto com a mesma equipe",
    imp_mes_tope: "O mes seguinte ja esta aberto",
    col_titular: "Titular",
    col_unidad: "Veiculo",
    col_ultimo_mes: "Ultimo mes",
    nav_central: "Monitoramento",
    nav_finanzas: "Despesas",
    nav_nomina: "Folha",
    nav_personal: "Equipe",
    sin_acceso: "Seu perfil nao tem acesso a esta tela.",

    /* Central de inteligencia y panorama */
    central_titulo: "Central de inteligencia",
    central_sub: "Atualiza sozinha a cada {s} segundos.",
    cen_sub: "Atualiza sozinha a cada {s} segundos. O urgente, em cima.",
    sc_titulo: "Dias sem fechar",
    sc_sub: "Dias que ja passaram e continuam abertos. Enquanto estiverem, essa equipe nao entra na folha.",
    sc_cuantos: "{n} pendentes",
    sc_dias: "aberto ha {n} dias",
    sc_horas: "aberto ha {n} horas",
    sc_sin_gente: "Sem pessoal designado",
    sc_arranco: "Comecou, nao fechou",
    sc_sin_marcas: "Sem nenhuma marcacao",
    sc_cerrar: "Fechar a mao",
    sc_cancelar: "Cancelar",
    sc_inicio: "Hora de inicio",
    sc_fin: "Hora de termino",
    sc_motivo: "Por que se fecha a mao",
    sc_motivo_ejemplo: "Ex: a equipe ficou sem bateria; confirmado por telefone com o coordenador as 19:40.",
    sc_falta_motivo: "Escreva pelo menos 10 caracteres. Daqui a tres meses esta nota vai ser a unica coisa que explique por que este dia nao tem marcacoes.",
    sc_advertencia: "Isto fica assinado com o seu nome e a hora. O dia entra na folha e fica marcado como fechado a mao.",
    sc_firmar: "Assinar e fechar o dia",
    sc_cerrado: "Dia fechado: {h} horas para {n} pessoas. Ja entra na folha.",
    cen_roto: "Atender agora",
    cen_panico: "Alerta de panico",
    cen_callado: "Sem reportar",
    cen_vencido: "Amanha sem resolver",
    cen_extra: "Prestes a entrar em hora extra",
    cen_manana: "Amanha · o meet and greet",
    cen_manana_sub: "A hora e aquela em que a equipe tem de estar no ponto, "
                    + "nao a do servico.",
    cen_manana_nada: "Amanha nao comeca nenhum servico.",
    cen_listos: "prontos",
    cen_incompletos: "incompletos",
    cen_corte: "Corte da vespera",
    cen_antes_del_corte: "O que falta ainda e trabalho do dia.",
    cen_paso_el_corte: "Passou o corte: o que falta tem de se resolver hoje a noite.",
    cen_equipo_llega: "A equipe chega",
    cen_servicio_inicia: "Servico",
    cen_contra_vuelo: "contra voo",
    cen_falta_uno: "falta 1 coisa",
    cen_faltan: "faltam {n} coisas",
    cen_todo_listo: "Tudo pronto",
    cen_ver_servicio: "Abrir o servico",
    cen_pulso: "Em curso",
    cen_pulso_sub: "O unico que a central nao consegue adivinhar e ha quanto "
                   + "tempo cada um esta calado.",
    cen_pulso_nada: "Nao ha servicos em curso.",
    cen_implantados: "Implantados em curso",
    cen_callado_min: "{n} min sem reportar",
    cen_nunca_reporto: "Ainda nao reportou",
    cen_ultimo: "Ultimo",
    cen_semana: "Os proximos dias",
    cen_semana_sub: "Para ver chegando a segunda-feira de seis servicos.",
    cen_sin_servicios: "sem servicos",
    cen_dia_completos: "{c} de {t} completos",
    cen_hito_llegada_origen: "Chegou ao ponto",
    cen_hito_contacto_ejecutivo: "Contato com o executivo",
    cen_hito_llegada_destino: "Chegou ao destino",
    cen_hito_salida_ruta: "Em rota",
    cen_hito_standby: "Em espera",
    cen_hito_fin_servicio: "Fim do servico",
    cen_p_punto_de_encuentro: "Ponto de encontro",
    cen_p_personal: "Pessoal",
    cen_p_rol: "Papel de cada um",
    cen_p_confirmacion: "Confirmacao da equipe",
    cen_p_unidad: "Unidade",
    cen_p_hoja: "Folha liberada",
    cen_p_vuelo: "Voo",
    cen_p_hora: "Hora confirmada",
    cen_p_viaticos: "Diarias depositadas",
    cen_p_hospitales: "Hospitais da cidade",
    central_alertas: "Alertas de incidente",
    central_sin_alertas: "Sem alertas abertos.",
    canal_boton_app: "Botao de panico (app)",
    canal_boton_vehiculo: "Botao do veiculo",
    canal_llamada: "Chamada",
    central_tomar: "Assumir",
    central_tomar_equipo: "Assumir e enviar equipe de resposta",
    central_alerta_tomada: "Alerta assumido",
    central_alerta_tomada_equipo: "Alerta assumido, equipe de resposta a caminho "
      + "Alerta assumido, equipe de resposta a caminho",
    central_alerta_cerrada: "Alerta encerrado",
    central_resolucion_ph: "O que aconteceu e como foi resolvido",
    central_falta_resolucion: "Escreva como foi resolvido",
    central_cerrar: "Encerrar",
    central_equipo_respuesta: "equipe de resposta",
    central_reportada: "Reportada",
    central_jornada: "jornada",
    central_ver_mapa: "Ver localizacao no mapa",
    central_proximos: "Proximos a iniciar",
    central_proximos_sub: "Servicos a menos de duas horas de comecar. A partir "
      + "daqui o acompanhamento e da central.",
    central_nada_proximo: "Nada comecando nas proximas duas horas.",
    central_listo: "pronto",
    central_pendiente: "pendente",
    col_servicio: "Servico",
    col_inicia: "Inicia",
    col_estado: "Estado",
    col_equipo: "Equipe",
    col_horario: "Horario",
    col_falta: "Falta",
    col_ultimo_reporte: "Ultimo relatorio",
    en_minutos: "em {n} min",
    hace_minutos: "ha {n} min",
    pan_titulo: "Operacao ao vivo",
    pan_sub: "Tudo o que esta acontecendo agora. Atualiza a cada "
      + "{s} segundos.",
    pan_requiere_atencion: "requer atencao",
    pan_alertas_sin_tomar: "Alertas de incidente sem responsavel",
    pan_alerta: "alerta",
    pan_alertas: "alertas",
    pan_esperando_central: "aguardando a central",
    pan_cada_una: "Cada um tem alguem do outro lado.",
    pan_en_curso: "Servicos em andamento",
    pan_en_curso_nota: "Com a equipe na rua agora",
    pan_por_iniciar: "Por iniciar (2 h)",
    pan_sin_estar_listos: "sem estar prontos",
    pan_todos_listos: "Todos prontos",
    pan_alertas_atencion: "Alertas em atendimento",
    pan_ya_tomadas: "A central ja assumiu",
    pan_arrancan_pronto: "Comecam logo e nao estao prontos",
    pan_en_la_calle: "Na rua agora",
    pan_sin_reportar: "sem relatorio",
    pan_por_horas_extra: "prestes a entrar em hora extra",
    pan_dinero: "Dinheiro em movimento",
    pan_viaticos_transferir: "Diarias a transferir",
    pan_asignaciones: "atribuicoes",
    pan_en_comprobacion: "Em comprovacao",
    pan_plazo_vencido: "com prazo vencido",
    pan_nomina_semana: "Folha da semana",
    pan_corte: "corte",
    pan_comprobacion_vencida: "Comprovacao vencida",
    pan_vencio: "venceu",
    pan_ajustes: "ajustes entram no proximo corte",
    pan_neto: "liquido",
    pan_camino_cobro: "Caminho ao faturamento",
    pan_cierres_abiertos: "Fechamentos abertos",
    pan_esperando_finanzas: "Aguardando o financeiro",
    pan_devueltos: "Devolvidos a operacao",
    pan_con_plazo_vencido: "Com prazo vencido",
    pan_regresados: "Devolvidos pelo financeiro",
    pan_sin_motivo: "sem motivo",
    pan_esperando_decision: "Aguardando uma decisao",
    pan_malas_calificaciones: "Avaliacoes ruins nao revisadas",
    pan_servicio: "servico",
    pan_de_5: "de 5",
    pan_incidencias_sin_vb: "Incidentes sem aprovacao do diretor",
    no_existe: "Essa tela nao existe.",
    idioma_puesto: "Console em portugues",

    cartera_titulo: "Servicos",
    cartera_sub: "Sua carteira e a dos consultores que voce esta cobrindo.",
    nuevo_servicio: "Novo servico",
    col_folio: "Numero",
    col_cliente: "Cliente",
    col_ejecutivo: "Executivo",
    col_tipo: "Tipo",
    col_estatus: "Status",
    col_equipos: "Equipes",

    personal_titulo: "Equipe de seguranca",
    personal_sub: "Nota de profissionalismo. A confianca avisa quando ha "
                + "poucas diarias avaliadas.",
    col_persona: "Pessoa",
    col_calificacion: "Nota",
    col_confianza: "Confianca",
    col_experiencia: "Experiencia",

    ts_titulo: "TS",
    ts_al_dia: "Cada download traz o mais recente: se moveram uma parada ha "
             + "pouco, o PDF ja a traz.",
    ts_sin_liberar: "Liberado ao confirmar a designacao.",
    ts_pdf: "TS em PDF",
    ts_ver: "Apenas ver",
    confirmar_ts: "Confirmar designacao e liberar o TS",
    confirmar_nota: "Verifique que o servico tenha tudo e libere o TS. Antes "
                  + "disso, a folha seria um rascunho.",
    confirmada_el: "Designacao confirmada em",
    ts_liberado: "O TS esta liberado: baixe e envie por e-mail.",

    alta_titulo: "Novo servico",
    alta_sub: "Com o minimo capturado o servico fica planejado. A equipe, o "
            + "veiculo e as diarias vem depois.",
    para_planeado: "Para ficar planejado",
    sin_servicios: "Ainda nao ha servicos cadastrados.",
    sin_ejecutivo: "Sem executivo",

    min_cliente: "Cliente",
    min_ciudad: "Cidade de cada equipe",
    min_solicitante: "Quem solicita",
    min_ejecutivo: "Executivo principal de cada equipe",
    min_dia: "Data e hora de inicio de cada equipe",
    min_inicio: "Ponto de inicio de cada equipe",
    falta_info: "Falta informacao",
    dar_de_alta: "Cadastrar",
    cancelar: "Cancelar",
    falta: "Falta",
    queda_planeado: "Com isso o servico fica planejado. Passa a designado "
                  + "quando tiver equipe e veiculo em todos os dias.",

    cliente: "Cliente",
    elige_cliente: "Selecione um cliente",
    tipo: "Tipo",
    eventual: "Eventual",
    implantado: "Implantado",
    consultor_asignado: "Consultor responsavel",
    pais: "Pais",
    ciudad_opera: "Cidade onde opera",
    otra_ciudad: "Outra cidade…",
    nombre_ciudad: "Nome da cidade",
    agregar: "Adicionar",
    escribe_ciudad: "Escreva o nome da cidade",
    ciudad_dada_alta: "foi cadastrada",

    quien_solicita: "Quem solicita",
    elegir_solicitante: "Escolher entre quem ja pede servicos deste cliente",
    nuevo_solicitante: "Novo solicitante",
    nuevo_solicitante_vacio: "Novo solicitante — este cliente nao tem nenhum",
    ya_registrado: "ja esta cadastrado",
    correo_campo: "E-mail",
    nombre: "Nome",
    apellido: "Sobrenome",
    telefono: "Telefone",

    equipos_titulo: "Equipes do servico",
    equipos_sub: "Cada equipe esta ligada a um executivo principal e leva seus "
               + "proprios dias, seu ponto de inicio e seu task sheet. Alfa, "
               + "Beta, Gamma: o sistema nomeia por ordem.",
    agregar_equipo: "Adicionar equipe",
    quitar_equipo: "Remover equipe",
    equipo: "Equipe",
    un_equipo_minimo: "O servico precisa de pelo menos uma equipe",
    ejecutivo_principal: "Executivo principal",
    ejecutivo_sub: "Quem esta equipe protege. Nome e sobrenome sao necessarios "
                 + "desde o cadastro; e-mail e telefone podem vir depois, "
                 + "servem para avisar que a equipe esta no ponto.",
    mismo_ejecutivo: "O mesmo executivo principal da equipe Alfa",

    inicio_y_dias: "Inicio e dias da equipe",
    inicio_y_dias_sub: "Onde comeca o dia 1 e os dias que a equipe cobre. "
                     + "Escreva o hotel, o terminal ou o endereco e escolha da "
                     + "lista: dai saem a cerca do motorista e os hospitais do "
                     + "task sheet.",
    direccion_encuentro: "Endereco do ponto de encontro",
    es_aeropuerto: "O ponto de encontro e um aeroporto",
    vuelo_llegada: "Voo de chegada do executivo principal",
    vuelo_llegada_sub: "A equipe chega 45 minutos antes do pouso.",
    aerolinea: "Companhia aerea",
    numero_vuelo: "Numero do voo",
    procedencia: "Procedencia",
    fecha_hora_llegada: "Data e hora de chegada",
    llega_antes: "A equipe chega antes",
    en_el_punto: "no ponto de encontro",
    antes_vuelo: "min antes do voo pousar",
    antes_presentacion: "min antes da hora de apresentacao",
    es_aeropuerto_aviso: "E um aeroporto: capture o voo de chegada",

    dias: "Dias",
    dias_sub: "A modalidade e de cada dia, nao do servico inteiro: o dia 1 pode "
            + "ser transfer e os seguintes diaria completa. A hora de "
            + "apresentacao e a do dia 1; os demais comecam com sua agenda.",
    dia_uno: "Dia 1 · inicio",
    dia_n: "Dia",
    fecha_col: "Data",
    modalidad: "Modalidade",
    presentacion: "Apresentacao",
    quitar: "Remover",
    agregar_dia: "Adicionar dia",
    un_dia_minimo: "A equipe precisa de pelo menos um dia",
    dia_con_fecha: "Cada equipe precisa de pelo menos um dia com data",
    agenda: "Agenda",
    cerrar_agenda: "Fechar agenda",
    agenda_opcional: "A agenda e opcional: ha clientes que nao a compartilham "
                   + "e o servico vai se desenvolvendo no caminho.",
    resumen_dia: "Resumo do dia",
    puntos_renglon: "Paradas, uma por linha",

    ajustar_pin: "Ajustar o pin e o raio da cerca",
    ajustar_pin_sub: "O pin e o do ponto de encontro e se preenche ao escolher "
                   + "no mapa. O raio e o circulo em volta desse pin que o "
                   + "motorista precisa pisar para marcar a chegada.",
    latitud: "Latitude",
    longitud: "Longitude",
    radio_metros: "Raio em metros",
    buscar_para_pin: "Busque o endereco para fixar o ponto e sua cerca.",
    buscando_punto: "Localizando o ponto…",
    abrir_google: "Abrir no Google Maps",
    sin_google: "A busca no Google nao esta configurada. Escreva o endereco e "
              + "fixe o pin a mao na secao abaixo.",
    pendiente_direccion: "Falta o endereco do ponto de encontro: sem ele o "
                       + "task sheet nao pode ser publicado.",
    pendiente_pin: "Falta fixar o ponto no mapa: sem suas coordenadas nao ha "
                 + "cerca nem hospitais proximos.",
    servicio_planeado: "planejado",
    servicio_borrador: "como rascunho",
    mod_full_day: "Diaria completa",
    mod_medio_dia: "Meia diaria",
    mod_transfer: "Transfer",
    ph_direccion: "Hotel, terminal ou endereco. Ex: Las Alcobas Polanco",
    agenda_cargada: " carregada",
    hora: "Hora",
    lugar_direccion: "Local e endereco",
    agregar_parada: "Adicionar parada",
    ph_parada: "Escritorio corporativo, Reforma 250 andar 12",
    buscar_hotel: "Buscar o hotel no Google",
  },
};

export function idioma() {
  try {
    const guardado = sessionStorage.getItem(LLAVE);
    if (TEXTOS[guardado]) return guardado;
  } catch { /* sin sessionStorage se usa el de siempre */ }
  return "es";
}

export function ponerIdioma(codigo) {
  try { sessionStorage.setItem(LLAVE, codigo); } catch { /* nada */ }
}

/* La clave se busca en el idioma puesto y, si falta, en espanol. */
export function t(clave) {
  const actual = TEXTOS[idioma()] || {};
  if (clave in actual) return actual[clave];
  return TEXTOS.es[clave] !== undefined ? TEXTOS.es[clave] : clave;
}

export function nombreIdioma(codigo = idioma()) {
  const i = IDIOMAS.find(x => x.codigo === codigo);
  return i ? i.nombre : codigo;
}
