# -*- coding: utf-8 -*-
"""Todas las horas de la bitacora, del pais del servicio (seccion 61).

Decision de Salvador, 24 de septiembre: "tiene que salir con la hora del
pais. igual y poner una nota para que el personal sepa".

  * Lo que toco la central, las notas de turno y las alertas salen con la
    hora de pared del pais del servicio, como las marcas. Antes salian
    con el reloj de la base: UTC en desarrollo, Mexico en el servidor.
  * La bitacora dice arriba de que pais son las horas.
  * Los "?" que toco el GPS dicen lo nuevo: el camino al punto, "En
    curso" y la bitacora. El recorrido de Monitoreo nombra lo que hay que
    atender ahora.
  * Las pruebas ya no pueden salir a Pegasus: conftest deja la conexion
    sin usuario, aunque el contenedor traiga el de verdad. Y la pausa por
    un 429 es de cada sitio.

Sin migracion. Idempotente. Todo se arma en memoria, se comprueba contra
lo que se probo (md5 por archivo) y solo entonces se escribe.
"""
import hashlib
import io
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent
B = RAIZ / "backend"

ARCHIVOS = {
    'bitacora_py': RAIZ / 'backend/app/bitacora.py',
    'bitacora_js': RAIZ / 'backend/app/web/bitacora.js',
    'idioma_js': RAIZ / 'backend/app/web/idioma.js',
    't_bitacora': RAIZ / 'backend/tests/test_bitacora.py',
    'pegasus': RAIZ / 'backend/app/pegasus.py',
    't_gps': RAIZ / 'backend/tests/test_gps.py',
    'conftest': RAIZ / 'backend/tests/conftest.py',
    'bitacora': RAIZ / 'BITACORA.md',
}
NUEVOS = {}
ESPERADO = {'bitacora_py': 'e2ec53ad5a52c99db882ae4affe4b43b', 'bitacora_js': '2ecf7a4569dd8d898a0237450ac5834d', 'idioma_js': '6baf2d8db10cea4db969e27d11284bbf', 't_bitacora': 'cc772a1b4c382f9e405ff5cc7d27a09b', 'pegasus': '4e7dfd3b969dbf74901658f601b77218', 't_gps': '1cc43adf73e6f346ea011ff4f9bc603b', 'conftest': '38a518d7ad46236630be9fe553f57c13', 'bitacora': '7df055c334fe329647df30a7545e0b3a'}

textos = {k: io.open(v, encoding="utf-8", newline="").read()
          for k, v in ARCHIVOS.items()}
saltados = []


def cambiar(clave, viejo, nuevo, marca=None):
    t = textos[clave]
    if (marca or nuevo) in t:
        saltados.append(clave)
        return
    assert t.count(viejo) == 1, (
        f"{clave}: '{viejo[:70]}...' esta {t.count(viejo)} veces. "
        "No se escribio nada.")
    textos[clave] = t.replace(viejo, nuevo)


cambiar('bitacora_py',
        '\nfrom app import gps\nfrom app import models as m\n\n# Cada renglon dice de donde salio. La pantalla los dibuja distinto, y\n# quien lee sabe si esta viendo una promesa o un hecho.\n',
        '\nfrom app import gps\nfrom app import models as m\nfrom app import reloj\n\n# Cada renglon dice de donde salio. La pantalla los dibuja distinto, y\n# quien lee sabe si esta viendo una promesa o un hecho.\n')

cambiar('bitacora_py',
        'def _hora_del_pais(db: Session, instante: datetime | None,\n                   jornada: m.Jornada):\n    """Un instante (con zona) en la hora de pared del servicio."""\n    from app import reloj\n\n    if instante is None:\n        return None\n    if instante.tzinfo is None:\n',
        'def _hora_del_pais(db: Session, instante: datetime | None,\n                   jornada: m.Jornada):\n    """Un instante (con zona) en la hora de pared del servicio."""\n    if instante is None:\n        return None\n    if instante.tzinfo is None:\n')

cambiar('bitacora_py',
        '    for alerta in (db.query(m.Alerta).filter_by(jornada_id=jornada_id).all()):\n        renglones.append({\n            "fuente": ALERTA,\n            "momento": (alerta.creada_en.replace(tzinfo=None)\n                        if alerta.creada_en else None),\n            "titulo": alerta.tipo.value,\n            "detalle": alerta.mensaje,\n            "marca": "atendida" if alerta.atendida else None,\n',
        '    for alerta in (db.query(m.Alerta).filter_by(jornada_id=jornada_id).all()):\n        renglones.append({\n            "fuente": ALERTA,\n            "momento": _hora_del_pais(db, alerta.creada_en, jornada),\n            "titulo": alerta.tipo.value,\n            "detalle": alerta.mensaje,\n            "marca": "atendida" if alerta.atendida else None,\n')

cambiar('bitacora_py',
        '        quien = registro.persona.nombre if registro.persona else None\n        renglones.append({\n            "fuente": CENTRAL,\n            "momento": (registro.creado_en.replace(tzinfo=None)\n                        if registro.creado_en else None),\n            "titulo": registro.accion,\n            "detalle": " · ".join(x for x in (registro.detalle, quien) if x),\n            "marca": None, "tono": "",\n',
        '        quien = registro.persona.nombre if registro.persona else None\n        renglones.append({\n            "fuente": CENTRAL,\n            "momento": _hora_del_pais(db, registro.creado_en, jornada),\n            "titulo": registro.accion,\n            "detalle": " · ".join(x for x in (registro.detalle, quien) if x),\n            "marca": None, "tono": "",\n')

cambiar('bitacora_py',
        '                 .filter_by(jornada_id=jornada_id).all()):\n        renglones.append({\n            "fuente": NOTA,\n            "momento": (nota.creada_en.replace(tzinfo=None)\n                        if nota.creada_en else None),\n            "titulo": nota.persona.nombre if nota.persona else "—",\n            "detalle": nota.texto,\n            "marca": None, "tono": "",\n',
        '                 .filter_by(jornada_id=jornada_id).all()):\n        renglones.append({\n            "fuente": NOTA,\n            "momento": _hora_del_pais(db, nota.creada_en, jornada),\n            "titulo": nota.persona.nombre if nota.persona else "—",\n            "detalle": nota.texto,\n            "marca": None, "tono": "",\n')

cambiar('bitacora_py',
        '         and j.estatus != m.EstatusJornada.CANCELADA),\n        key=lambda j: j.fecha, default=None)\n\n    return {\n        "jornada_id": jornada.id,\n        "fecha": jornada.fecha.isoformat(),\n        "estatus_jornada": jornada.estatus.value,\n        "meet_and_greet": _meet_and_greet(db, jornada),\n        "manana": ({"jornada_id": siguiente.id,\n',
        '         and j.estatus != m.EstatusJornada.CANCELADA),\n        key=lambda j: j.fecha, default=None)\n\n    # Todas las horas de arriba son de la pared del pais del servicio, y\n    # la pantalla lo dice: quien lo lee puede estar en otro pais.\n    pais_id = reloj.pais_de_la_jornada(jornada)\n    pais = db.get(m.Pais, pais_id) if pais_id else None\n\n    return {\n        "jornada_id": jornada.id,\n        "fecha": jornada.fecha.isoformat(),\n        "hora_de": pais.nombre if pais else None,\n        "estatus_jornada": jornada.estatus.value,\n        "meet_and_greet": _meet_and_greet(db, jornada),\n        "manana": ({"jornada_id": siguiente.id,\n')

cambiar('bitacora_js',
        '\n  zona.replaceChildren(\n    conAyuda("div", leyenda, "ay_bitacora", { clase: "leyenda_bitacora" }),\n    ...(todos.length\n      ? todos.map(r => renglon(r, d, refrescar))\n      : [h("div", { clase: "vacio" }, t("bit_vacia"))]),\n',
        '\n  zona.replaceChildren(\n    conAyuda("div", leyenda, "ay_bitacora", { clase: "leyenda_bitacora" }),\n    /* Todas las horas son de la pared del pais del servicio, y se dice:\n       la central de un pais lee la bitacora de otro. */\n    d.hora_de\n      ? h("div", { clase: "gris chico", style: "margin:-4px 0 10px" },\n          t("bit_horas_de").replace("{pais}", d.hora_de))\n      : "",\n    ...(todos.length\n      ? todos.map(r => renglon(r, d, refrescar))\n      : [h("div", { clase: "vacio" }, t("bit_vacia"))]),\n')

cambiar('idioma_js',
        '    rec_operacion: "Cómo va la operación ahora mismo: quién está en la calle, quién no ha reportado y qué se ve en el día.",\n    rec_eventuales: "Los servicios que se contratan por día: el alta, la cotización, quién va y el cierre.",\n    rec_implantados: "Los servicios de mes, con la misma gente todos los días. De aquí salen el calendario y la facturación mensual.",\n    rec_central: "Lo que hay que resolver antes del corte de la víspera: quién no ha confirmado, qué viático no se depositó, qué hoja falta liberar.",\n    rec_finanzas: "El dinero del servicio: lo que se entregó, lo que falta comprobar, las compras y las rentas.",\n    rec_nomina: "Lo que se le paga al personal de seguridad cada semana, día por día y con el rol de ese día.",\n    rec_personal: "Tu gente y tu flota: quién está disponible, con qué capacitación, y qué unidad puede llevar.",\n',
        '    rec_operacion: "Cómo va la operación ahora mismo: quién está en la calle, quién no ha reportado y qué se ve en el día.",\n    rec_eventuales: "Los servicios que se contratan por día: el alta, la cotización, quién va y el cierre.",\n    rec_implantados: "Los servicios de mes, con la misma gente todos los días. De aquí salen el calendario y la facturación mensual.",\n    rec_central: "Lo que hay que atender ahora —un pánico, un inhibidor, un equipo callado— y lo que hay que resolver antes del corte de la víspera: quién no ha confirmado, qué viático no se depositó, qué hoja falta liberar.",\n    rec_finanzas: "El dinero del servicio: lo que se entregó, lo que falta comprobar, las compras y las rentas.",\n    rec_nomina: "Lo que se le paga al personal de seguridad cada semana, día por día y con el rol de ese día.",\n    rec_personal: "Tu gente y tu flota: quién está disponible, con qué capacitación, y qué unidad puede llevar.",\n')

cambiar('idioma_js',
        '    ay_pan_calidad_para: "Saber si lo que nos reportan es cierto, no si la operación va bien. Son dos preguntas distintas.",\n    ay_pan_calidad_cuando: "Nunca de golpe: estas cifras solo se ven al cerrar cada servicio, una por una. Un patrón —alguien que siempre marca desde lejos— no se ve así.",\n    ay_pan_calidad_numero: "Los intentos fuera de geocerca son marcas rechazadas: alguien quiso reportar que ya llegó desde lejos. Las marcas por validar las tiene que revisar la central.",\n    ay_cen_pulso_para: "Ver los servicios que están corriendo ahora y, sobre todo, cuánto lleva callado cada uno.",\n    ay_cen_camino_para: "Saber si va a haber alguien en el punto. No mide "\n      + "puntualidad: mide si la persona se está moviendo hacia allá.",\n    ay_cen_camino_cuando: "Cuando alguien aparece aquí como \\"Sin "\n      + "respuesta\\" o \\"No llega\\". A esa hora todavía se puede mandar a "\n      + "otra persona; una hora después, ya no.",\n    ay_cen_pulso_cuando: "Cuando el equipo vuelve a reportar y todo estaba bien. O cuando no vuelve, y entonces ya pasó algo.",\n    ay_cen_pulso_numero: "El silencio se cuenta desde la última marca o reporte de ese equipo, con la hora de su país.",\n    ay_cen_semana_para: "Ver lo que viene, para llegar antes: confirmaciones que faltan, gente sin asignar, viáticos sin depositar.",\n    ay_cen_semana_cuando: "A las seis de la mañana del día del servicio, que es cuando lo que se resolvía con una llamada la víspera ya cuesta un servicio.",\n    ay_cen_sin_cerrar_para: "La lista de trabajo de la central: días que ya pasaron y siguen abiertos.",\n',
        '    ay_pan_calidad_para: "Saber si lo que nos reportan es cierto, no si la operación va bien. Son dos preguntas distintas.",\n    ay_pan_calidad_cuando: "Nunca de golpe: estas cifras solo se ven al cerrar cada servicio, una por una. Un patrón —alguien que siempre marca desde lejos— no se ve así.",\n    ay_pan_calidad_numero: "Los intentos fuera de geocerca son marcas rechazadas: alguien quiso reportar que ya llegó desde lejos. Las marcas por validar las tiene que revisar la central.",\n    ay_cen_pulso_para: "Ver los servicios que están corriendo ahora y, sobre todo, cuánto lleva callado cada uno. Debajo va lo que dice su unidad.",\n    ay_cen_camino_para: "Saber si va a haber alguien en el punto. No mide "\n      + "puntualidad: mide si la persona se está moviendo hacia allá. Para "\n      + "quien trae unidad, lo que tiene que llegar es la camioneta, y su GPS "\n      + "cuenta como si hubiera contestado.",\n    ay_cen_camino_cuando: "Cuando alguien aparece aquí como \\"Sin "\n      + "respuesta\\", \\"No llega\\" o \\"La unidad no ha salido\\". A esa hora "\n      + "todavía se puede mandar a otra persona; una hora después, ya no.",\n    ay_cen_camino_numero: "Las distancias son en línea recta al punto: la "\n      + "del teléfono, de la última posición que mandó; la de la unidad, de "\n      + "su último reporte.",\n    ay_cen_pulso_cuando: "Cuando el equipo vuelve a reportar y todo estaba bien. O cuando no vuelve, y entonces ya pasó algo.",\n    ay_cen_pulso_numero: "El silencio se cuenta desde la última marca o reporte de ese equipo, con la hora de su país. La unidad no cuenta como reporte: un equipo callado sigue en rojo aunque su camioneta se mueva.",\n    ay_cen_semana_para: "Ver lo que viene, para llegar antes: confirmaciones que faltan, gente sin asignar, viáticos sin depositar.",\n    ay_cen_semana_cuando: "A las seis de la mañana del día del servicio, que es cuando lo que se resolvía con una llamada la víspera ya cuesta un servicio.",\n    ay_cen_sin_cerrar_para: "La lista de trabajo de la central: días que ya pasaron y siguen abiertos.",\n')

cambiar('idioma_js',
        '    /* --- bitacora del dia */\n    bit_ver: "Bitácora",\n    bit_cerrar: "Cerrar bitácora",\n    ay_bitacora_para: "Ver en una sola columna todo lo que pasó en el día: lo que el cliente pidió, lo que el equipo marcó desde la app, lo que el sistema alertó y lo que la central tocó a mano.",\n    ay_bitacora_cuando: "Cuando el día no salió como estaba escrito y hay que reconstruir en qué momento se separó del plan. Un renglón sin hora es una parada que se planeó y que nadie marcó. Las posiciones del camino al punto no están aquí a propósito: se apagan al marcar la llegada y esto no es un rastreo.",\n    dia_titulo: "Lo que pasó ese día",\n    dia_sin_marca: "Todavía no hay meet and greet: nadie ha marcado el contacto con el ejecutivo.",\n    dia_programado: "Programado para las",\n',
        '    /* --- bitacora del dia */\n    bit_ver: "Bitácora",\n    bit_cerrar: "Cerrar bitácora",\n    ay_bitacora_para: "Ver en una sola columna todo lo que pasó en el día: lo que el cliente pidió, lo que el equipo marcó desde la app —con dónde estaba su unidad en ese momento—, lo que el sistema alertó y lo que la central tocó a mano.",\n    ay_bitacora_cuando: "Cuando el día no salió como estaba escrito y hay que reconstruir en qué momento se separó del plan. Un renglón sin hora es una parada que se planeó y que nadie marcó. Las posiciones del camino al punto no están aquí a propósito: se apagan al marcar la llegada y esto no es un rastreo; de la unidad entra una sola medida por marca.",\n    ay_bitacora_numero: "Todas las horas son del país del servicio, aunque quien lo lea esté en otro.",\n    dia_titulo: "Lo que pasó ese día",\n    dia_sin_marca: "Todavía no hay meet and greet: nadie ha marcado el contacto con el ejecutivo.",\n    dia_programado: "Programado para las",\n')

cambiar('idioma_js',
        '    cmp_quitar_foto: "Quitar",\n    cmp_borrador_recuperado: "Se recuperó lo que llevabas capturado.",\n    bit_vacia: "Todavía no hay nada que contar de este día.",\n    bit_sin_hora: "sin hora",\n    bit_fuente_plan: "Agenda del cliente",\n    bit_fuente_hito: "Lo que marcó el equipo",\n',
        '    cmp_quitar_foto: "Quitar",\n    cmp_borrador_recuperado: "Se recuperó lo que llevabas capturado.",\n    bit_vacia: "Todavía no hay nada que contar de este día.",\n    bit_horas_de: "Todas las horas están en hora de {pais}.",\n    bit_sin_hora: "sin hora",\n    bit_fuente_plan: "Agenda del cliente",\n    bit_fuente_hito: "Lo que marcó el equipo",\n')

cambiar('idioma_js',
        '    rec_operacion: "How the operation is going right now: who is out there, who has not reported and what the day looks like.",\n    rec_eventuales: "Services hired by the day: intake, quote, who goes and closing.",\n    rec_implantados: "Monthly services, with the same people every day. The calendar and the monthly invoice come from here.",\n    rec_central: "What has to be solved before the evening cut-off: who has not confirmed, which expense money was not deposited, which sheet is not released yet.",\n    rec_finanzas: "The money of the service: what was handed out, what is still to be accounted for, purchases and rentals.",\n    rec_nomina: "What field officers are paid each week, day by day and with that day\'s role.",\n    rec_personal: "Your people and your fleet: who is available, with what training, and which vehicle they can take.",\n',
        '    rec_operacion: "How the operation is going right now: who is out there, who has not reported and what the day looks like.",\n    rec_eventuales: "Services hired by the day: intake, quote, who goes and closing.",\n    rec_implantados: "Monthly services, with the same people every day. The calendar and the monthly invoice come from here.",\n    rec_central: "What needs attention now —a panic alert, a jammer, a silent team— and what has to be solved before the evening cut-off: who has not confirmed, which expense money was not deposited, which sheet is not released yet.",\n    rec_finanzas: "The money of the service: what was handed out, what is still to be accounted for, purchases and rentals.",\n    rec_nomina: "What field officers are paid each week, day by day and with that day\'s role.",\n    rec_personal: "Your people and your fleet: who is available, with what training, and which vehicle they can take.",\n')

cambiar('idioma_js',
        '    ay_pan_calidad_para: "Know whether what gets reported to us is true — not whether operations are going well. Two different questions.",\n    ay_pan_calidad_cuando: "Never all at once: these figures only show when closing each service, one by one. A pattern — someone who always checks in from far away — does not show that way.",\n    ay_pan_calidad_numero: "Out-of-geofence attempts are rejected check-ins: someone tried to report arriving from far away. Check-ins to validate have to be reviewed by the control room.",\n    ay_cen_pulso_para: "See the services running right now and, above all, how long each one has been silent.",\n    ay_cen_camino_para: "Know whether someone will be at the meeting "\n      + "point. It does not measure punctuality: it measures whether "\n      + "the person is moving towards it.",\n    ay_cen_camino_cuando: "When someone shows up here as \\"No answer\\" or "\n      + "\\"Will not make it\\". At that hour another person can still be "\n      + "sent; an hour later, no.",\n    ay_cen_pulso_cuando: "When the team checks in again and everything was fine. Or when they do not, and by then something has happened.",\n    ay_cen_pulso_numero: "Silence is counted from that team\'s last check-in or report, in their country\'s time.",\n    ay_cen_semana_para: "See what is coming, to get ahead of it: missing confirmations, unassigned people, allowances not yet paid.",\n    ay_cen_semana_cuando: "At six in the morning on the day of the service, when what one phone call the night before would have solved now costs a service.",\n    ay_cen_sin_cerrar_para: "The control room\'s worklist: days that have already passed and are still open.",\n',
        '    ay_pan_calidad_para: "Know whether what gets reported to us is true — not whether operations are going well. Two different questions.",\n    ay_pan_calidad_cuando: "Never all at once: these figures only show when closing each service, one by one. A pattern — someone who always checks in from far away — does not show that way.",\n    ay_pan_calidad_numero: "Out-of-geofence attempts are rejected check-ins: someone tried to report arriving from far away. Check-ins to validate have to be reviewed by the control room.",\n    ay_cen_pulso_para: "See the services running right now and, above all, how long each one has been silent. Below it, what its vehicle says.",\n    ay_cen_camino_para: "Know whether someone will be at the meeting "\n      + "point. It does not measure punctuality: it measures whether "\n      + "the person is moving towards it. For whoever brings a vehicle, "\n      + "what has to arrive is the vehicle, and its GPS counts as if they "\n      + "had answered.",\n    ay_cen_camino_cuando: "When someone shows up here as \\"No answer\\", "\n      + "\\"Will not make it\\" or \\"The vehicle has not left\\". At that hour "\n      + "another person can still be sent; an hour later, no.",\n    ay_cen_camino_numero: "Distances are in a straight line to the point: "\n      + "the phone\'s from the last position it sent, the vehicle\'s from its "\n      + "last report.",\n    ay_cen_pulso_cuando: "When the team checks in again and everything was fine. Or when they do not, and by then something has happened.",\n    ay_cen_pulso_numero: "Silence is counted from that team\'s last check-in or report, in their country\'s time. The vehicle does not count as a report: a silent team stays red even if its vehicle is moving.",\n    ay_cen_semana_para: "See what is coming, to get ahead of it: missing confirmations, unassigned people, allowances not yet paid.",\n    ay_cen_semana_cuando: "At six in the morning on the day of the service, when what one phone call the night before would have solved now costs a service.",\n    ay_cen_sin_cerrar_para: "The control room\'s worklist: days that have already passed and are still open.",\n')

cambiar('idioma_js',
        '    /* --- bitacora del dia */\n    bit_ver: "Day log",\n    bit_cerrar: "Close log",\n    ay_bitacora_para: "See everything that happened during the day in one column: what the client asked for, what the team marked from the app, what the system flagged and what the control room did by hand.",\n    ay_bitacora_cuando: "When the day did not go as written and you need to pin down where it split from the plan. A row with no time is a stop that was planned and never marked. Positions on the way to the pickup are deliberately absent: they switch off on arrival and this is not a tracker.",\n    dia_titulo: "What actually happened that day",\n    dia_sin_marca: "No meet and greet yet: nobody has marked the contact with the executive.",\n    dia_programado: "Scheduled for",\n',
        '    /* --- bitacora del dia */\n    bit_ver: "Day log",\n    bit_cerrar: "Close log",\n    ay_bitacora_para: "See everything that happened during the day in one column: what the client asked for, what the team marked from the app —with where its vehicle was at that moment—, what the system flagged and what the control room did by hand.",\n    ay_bitacora_cuando: "When the day did not go as written and you need to pin down where it split from the plan. A row with no time is a stop that was planned and never marked. Positions on the way to the pickup are deliberately absent: they switch off on arrival and this is not a tracker; from the vehicle there is a single reading per check-in.",\n    ay_bitacora_numero: "All times are the service country\'s, even if whoever reads it is somewhere else.",\n    dia_titulo: "What actually happened that day",\n    dia_sin_marca: "No meet and greet yet: nobody has marked the contact with the executive.",\n    dia_programado: "Scheduled for",\n')

cambiar('idioma_js',
        '    cmp_quitar_foto: "Remove",\n    cmp_borrador_recuperado: "Recovered what you had captured.",\n    bit_vacia: "Nothing to tell about this day yet.",\n    bit_sin_hora: "no time",\n    bit_fuente_plan: "Client agenda",\n    bit_fuente_hito: "What the team marked",\n',
        '    cmp_quitar_foto: "Remove",\n    cmp_borrador_recuperado: "Recovered what you had captured.",\n    bit_vacia: "Nothing to tell about this day yet.",\n    bit_horas_de: "All times are {pais} time.",\n    bit_sin_hora: "no time",\n    bit_fuente_plan: "Client agenda",\n    bit_fuente_hito: "What the team marked",\n')

cambiar('idioma_js',
        '    rec_operacion: "Como está a operação agora: quem está na rua, quem não reportou e como está o dia.",\n    rec_eventuales: "Os serviços contratados por dia: o cadastro, a cotação, quem vai e o fechamento.",\n    rec_implantados: "Os serviços de mês, com a mesma gente todos os dias. Daqui saem o calendário e o faturamento mensal.",\n    rec_central: "O que precisa ser resolvido antes do corte da véspera: quem não confirmou, qual diária não foi depositada, qual folha falta liberar.",\n    rec_finanzas: "O dinheiro do serviço: o que foi entregue, o que falta comprovar, as compras e as locações.",\n    rec_nomina: "O que se paga ao pessoal de segurança a cada semana, dia a dia e com a função daquele dia.",\n    rec_personal: "Sua gente e sua frota: quem está disponível, com que treinamento, e que unidade pode levar.",\n',
        '    rec_operacion: "Como está a operação agora: quem está na rua, quem não reportou e como está o dia.",\n    rec_eventuales: "Os serviços contratados por dia: o cadastro, a cotação, quem vai e o fechamento.",\n    rec_implantados: "Os serviços de mês, com a mesma gente todos os dias. Daqui saem o calendário e o faturamento mensal.",\n    rec_central: "O que precisa de atenção agora —um pânico, um bloqueador de sinal, uma equipe calada— e o que precisa ser resolvido antes do corte da véspera: quem não confirmou, qual diária não foi depositada, qual folha falta liberar.",\n    rec_finanzas: "O dinheiro do serviço: o que foi entregue, o que falta comprovar, as compras e as locações.",\n    rec_nomina: "O que se paga ao pessoal de segurança a cada semana, dia a dia e com a função daquele dia.",\n    rec_personal: "Sua gente e sua frota: quem está disponível, com que treinamento, e que unidade pode levar.",\n')

cambiar('idioma_js',
        '    ay_pan_calidad_para: "Saber se o que nos reportam é verdade, não se a operação vai bem. São duas perguntas distintas.",\n    ay_pan_calidad_cuando: "Nunca de uma vez: estes números só aparecem ao fechar cada serviço, um a um. Um padrão — alguém que sempre marca de longe — não se vê assim.",\n    ay_pan_calidad_numero: "As tentativas fora da cerca são marcações recusadas: alguém quis reportar que já chegou estando longe. As marcações a validar têm de ser revistas pela central.",\n    ay_cen_pulso_para: "Ver os serviços em curso agora e, sobretudo, há quanto tempo cada um está calado.",\n    ay_cen_camino_para: "Saber se vai ter alguém no ponto. Não mede "\n      + "pontualidade: mede se a pessoa está se movendo para lá.",\n    ay_cen_camino_cuando: "Quando alguém aparece aqui como \\"Sem "\n      + "resposta\\" ou \\"Não chega\\". Nessa hora ainda dá para mandar "\n      + "outra pessoa; uma hora depois, não.",\n    ay_cen_pulso_cuando: "Quando a equipe volta a reportar e estava tudo bem. Ou quando não volta, e aí já aconteceu algo.",\n    ay_cen_pulso_numero: "O silêncio é contado desde a última marcação ou reporte daquela equipe, com a hora do país dela.",\n    ay_cen_semana_para: "Ver o que vem, para chegar antes: confirmações que faltam, gente sem atribuir, diárias sem depositar.",\n    ay_cen_semana_cuando: "Às seis da manhã do dia do serviço, quando o que se resolvia com um telefonema na véspera já custa um serviço.",\n    ay_cen_sin_cerrar_para: "A lista de trabalho da central: dias que já passaram e continuam abertos.",\n',
        '    ay_pan_calidad_para: "Saber se o que nos reportam é verdade, não se a operação vai bem. São duas perguntas distintas.",\n    ay_pan_calidad_cuando: "Nunca de uma vez: estes números só aparecem ao fechar cada serviço, um a um. Um padrão — alguém que sempre marca de longe — não se vê assim.",\n    ay_pan_calidad_numero: "As tentativas fora da cerca são marcações recusadas: alguém quis reportar que já chegou estando longe. As marcações a validar têm de ser revistas pela central.",\n    ay_cen_pulso_para: "Ver os serviços em curso agora e, sobretudo, há quanto tempo cada um está calado. Embaixo vai o que diz a unidade.",\n    ay_cen_camino_para: "Saber se vai ter alguém no ponto. Não mede "\n      + "pontualidade: mede se a pessoa está se movendo para lá. Para quem "\n      + "leva unidade, o que tem que chegar é a camionete, e o GPS dela "\n      + "conta como se tivesse respondido.",\n    ay_cen_camino_cuando: "Quando alguém aparece aqui como \\"Sem "\n      + "resposta\\", \\"Não chega\\" ou \\"A unidade não saiu\\". Nessa hora "\n      + "ainda dá para mandar outra pessoa; uma hora depois, não.",\n    ay_cen_camino_numero: "As distâncias são em linha reta até o ponto: a "\n      + "do telefone, da última posição que mandou; a da unidade, do seu "\n      + "último reporte.",\n    ay_cen_pulso_cuando: "Quando a equipe volta a reportar e estava tudo bem. Ou quando não volta, e aí já aconteceu algo.",\n    ay_cen_pulso_numero: "O silêncio é contado desde a última marcação ou reporte daquela equipe, com a hora do país dela. A unidade não conta como reporte: uma equipe calada continua em vermelho mesmo que a camionete se mova.",\n    ay_cen_semana_para: "Ver o que vem, para chegar antes: confirmações que faltam, gente sem atribuir, diárias sem depositar.",\n    ay_cen_semana_cuando: "Às seis da manhã do dia do serviço, quando o que se resolvia com um telefonema na véspera já custa um serviço.",\n    ay_cen_sin_cerrar_para: "A lista de trabalho da central: dias que já passaram e continuam abertos.",\n')

cambiar('idioma_js',
        '    /* --- bitacora del dia */\n    bit_ver: "Diário do dia",\n    bit_cerrar: "Fechar diário",\n    ay_bitacora_para: "Ver numa só coluna tudo o que aconteceu no dia: o que o cliente pediu, o que a equipe marcou pelo aplicativo, o que o sistema alertou e o que a central fez à mão.",\n    ay_bitacora_cuando: "Quando o dia não saiu como estava escrito e é preciso reconstruir em que momento se separou do plano. Uma linha sem hora é uma parada que foi planejada e que ninguém marcou. As posições do caminho até o ponto não estão aqui de propósito: apagam-se ao marcar a chegada e isto não é um rastreamento.",\n    dia_titulo: "O que aconteceu naquele dia",\n    dia_sin_marca: "Ainda não há meet and greet: ninguém marcou o contato com o executivo.",\n    dia_programado: "Programado para as",\n',
        '    /* --- bitacora del dia */\n    bit_ver: "Diário do dia",\n    bit_cerrar: "Fechar diário",\n    ay_bitacora_para: "Ver numa só coluna tudo o que aconteceu no dia: o que o cliente pediu, o que a equipe marcou pelo aplicativo —com onde estava a unidade naquele momento—, o que o sistema alertou e o que a central fez à mão.",\n    ay_bitacora_cuando: "Quando o dia não saiu como estava escrito e é preciso reconstruir em que momento se separou do plano. Uma linha sem hora é uma parada que foi planejada e que ninguém marcou. As posições do caminho até o ponto não estão aqui de propósito: apagam-se ao marcar a chegada e isto não é um rastreamento; da unidade entra uma só medida por marcação.",\n    ay_bitacora_numero: "Todos os horários são do país do serviço, mesmo que quem lê esteja em outro.",\n    dia_titulo: "O que aconteceu naquele dia",\n    dia_sin_marca: "Ainda não há meet and greet: ninguém marcou o contato com o executivo.",\n    dia_programado: "Programado para as",\n')

cambiar('idioma_js',
        '    cmp_quitar_foto: "Remover",\n    cmp_borrador_recuperado: "Recuperado o que você tinha capturado.",\n    bit_vacia: "Ainda não há nada para contar deste dia.",\n    bit_sin_hora: "sem hora",\n    bit_fuente_plan: "Agenda do cliente",\n    bit_fuente_hito: "O que a equipe marcou",\n',
        '    cmp_quitar_foto: "Remover",\n    cmp_borrador_recuperado: "Recuperado o que você tinha capturado.",\n    bit_vacia: "Ainda não há nada para contar deste dia.",\n    bit_horas_de: "Todos os horários estão no horário de {pais}.",\n    bit_sin_hora: "sem hora",\n    bit_fuente_plan: "Agenda do cliente",\n    bit_fuente_hito: "O que a equipe marcou",\n')

cambiar('t_bitacora',
        '        db.close()\n\n\ndef test_una_marca_diferida_ensena_las_dos_horas(cliente, sesion, datos):\n    """La app puede marcar sin señal y mandar después. Hasta hoy esa\n    diferencia no se enseñaba en ningún lado, y un día donde todo llega\n',
        '        db.close()\n\n\ndef test_todas_las_horas_son_del_pais_del_servicio(cliente, sesion, datos):\n    """Lo que toco la central, las notas y las alertas se guardan como un\n    instante, y salian con el reloj de la base: en UTC en desarrollo, en\n    hora de Mexico en el servidor aunque el servicio fuera de Brasil. Van\n    con la hora de pared del pais del servicio, como las marcas, y la\n    bitacora dice cual es."""\n    from datetime import timezone\n\n    from app import auditoria, bitacora, models as m\n    from app.db import SessionLocal\n\n    servicio, j = _dia(cliente, sesion, datos, 0)\n    # Un instante de UTC que en Mexico (UTC-6) cae a las 18:21 del dia\n    # anterior: si alguien olvida convertir, se nota en la fecha tambien.\n    instante = datetime(2026, 9, 24, 0, 21, tzinfo=timezone.utc)\n    en_mexico = datetime(2026, 9, 23, 18, 21)\n\n    db = SessionLocal()\n    try:\n        fila = db.get(m.Servicio, servicio["id"])\n        usuario = (db.query(m.Usuario)\n                   .filter_by(correo="ana.solis@centauro.lat").one())\n        auditoria.registrar(db, usuario, fila, "cerrar dia a mano",\n                            "nadie marco el fin", jornada_id=j["id"])\n        db.flush()\n        (db.query(m.RegistroAccion).filter_by(jornada_id=j["id"])\n         .update({"creado_en": instante}))\n        db.add(m.NotaBitacora(jornada_id=j["id"], persona_id=usuario.persona_id,\n                              texto="Hablo el cliente", creada_en=instante))\n        db.add(m.Alerta(jornada_id=j["id"], tipo=m.TipoAlerta.SIN_REPORTE,\n                        mensaje="Sin reportar", creada_en=instante))\n        db.commit()\n\n        d = bitacora.del_dia(db, j["id"])\n        assert d["hora_de"] == "Mexico"\n        horas = {r["fuente"]: r["momento"] for r in d["renglones"]\n                 if r["fuente"] in ("central", "nota", "alerta")}\n        assert set(horas) == {"central", "nota", "alerta"}\n        for fuente, momento in horas.items():\n            assert datetime.fromisoformat(momento) == en_mexico, fuente\n    finally:\n        db.close()\n\n\ndef test_una_marca_diferida_ensena_las_dos_horas(cliente, sesion, datos):\n    """La app puede marcar sin señal y mandar después. Hasta hoy esa\n    diferencia no se enseñaba en ningún lado, y un día donde todo llega\n')

cambiar('pegasus',
        '# minutos serian treinta entradas por hora con la misma clave.\n_sesiones: dict[tuple, str] = {}\n\n# La pausa despues de un 429. Vive en Redis para que la respeten todos los\n# procesos --el worker de Celery tiene varios--; si Redis no contesta, al\n# menos la respeta este.\nLLAVE_PAUSA = "pegasus:pausa_hasta"\nESPERA_SIN_AVISO = 15 * 60      # segundos, si el 429 no dice hasta cuando\nESPERA_MAXIMA = 60 * 60\n_pausa_local = 0.0\n_redis_cliente = None\n\n\n',
        '# minutos serian treinta entradas por hora con la misma clave.\n_sesiones: dict[tuple, str] = {}\n\n# La pausa despues de un 429, por sitio. Vive en Redis para que la\n# respeten todos los procesos --el worker de Celery tiene varios--; si\n# Redis no contesta, al menos la respeta este.\nLLAVE_PAUSA = "pegasus:pausa_hasta"\nESPERA_SIN_AVISO = 15 * 60      # segundos, si el 429 no dice hasta cuando\nESPERA_MAXIMA = 60 * 60\n_pausa_local: dict[str, float] = {}\n_redis_cliente = None\n\n\n')

cambiar('pegasus',
        '    return _redis_cliente or None\n\n\ndef pausa_hasta() -> float:\n    """Hasta cuando (epoch) no se le pide nada a Pegasus; 0 si se puede."""\n    guardada = 0.0\n    r = _redis()\n    if r is not None:\n        try:\n            guardada = float(r.get(LLAVE_PAUSA) or 0)\n        except Exception:                                  # noqa: BLE001\n            guardada = 0.0\n    return max(guardada, _pausa_local)\n\n\ndef _pausar(respuesta) -> float:\n    """Pegasus dijo 429: hasta cuando no se le pide nada."""\n    global _pausa_local\n    ahora = time.time()\n    try:\n        hasta = float(respuesta.headers.get("X-RateLimit-Reset") or 0)\n',
        '    return _redis_cliente or None\n\n\ndef _llave(sitio: str) -> str:\n    return f"{LLAVE_PAUSA}:{sitio}"\n\n\ndef pausa_hasta(sitio: str) -> float:\n    """Hasta cuando (epoch) no se le pide nada a ese sitio; 0 si se puede."""\n    guardada = 0.0\n    r = _redis()\n    if r is not None:\n        try:\n            guardada = float(r.get(_llave(sitio)) or 0)\n        except Exception:                                  # noqa: BLE001\n            guardada = 0.0\n    return max(guardada, _pausa_local.get(sitio, 0.0))\n\n\ndef _pausar(respuesta, sitio: str) -> float:\n    """Pegasus dijo 429: hasta cuando no se le pide nada a ese sitio."""\n    ahora = time.time()\n    try:\n        hasta = float(respuesta.headers.get("X-RateLimit-Reset") or 0)\n')

cambiar('pegasus',
        '    if hasta <= ahora:\n        hasta = ahora + ESPERA_SIN_AVISO\n    hasta = min(hasta, ahora + ESPERA_MAXIMA) + 5\n    _pausa_local = hasta\n    r = _redis()\n    if r is not None:\n        try:\n            r.set(LLAVE_PAUSA, hasta, ex=int(hasta - ahora) + 1)\n        except Exception:                                  # noqa: BLE001\n            pass\n    return hasta\n\n\ndef quitar_pausa() -> None:\n    """Para las pruebas: olvida la pausa."""\n    global _pausa_local\n    _pausa_local = 0.0\n    r = _redis()\n    if r is not None:\n        try:\n            r.delete(LLAVE_PAUSA)\n        except Exception:                                  # noqa: BLE001\n            pass\n\n',
        '    if hasta <= ahora:\n        hasta = ahora + ESPERA_SIN_AVISO\n    hasta = min(hasta, ahora + ESPERA_MAXIMA) + 5\n    _pausa_local[sitio] = hasta\n    r = _redis()\n    if r is not None:\n        try:\n            r.set(_llave(sitio), hasta, ex=int(hasta - ahora) + 1)\n        except Exception:                                  # noqa: BLE001\n            pass\n    return hasta\n\n\ndef quitar_pausa(sitio: str) -> None:\n    """Para las pruebas: olvida la pausa de ese sitio, y solo de ese."""\n    _pausa_local.pop(sitio, None)\n    r = _redis()\n    if r is not None:\n        try:\n            r.delete(_llave(sitio))\n        except Exception:                                  # noqa: BLE001\n            pass\n\n')

cambiar('pegasus',
        '        except httpx.HTTPError as e:\n            raise NoResponde(f"Pegasus no contesto ({type(e).__name__}).")\n        if r.status_code == 429:\n            raise NoResponde(_mensaje_de_pausa(_pausar(r)))\n        if r.status_code != 200:\n            raise NoResponde(f"Pegasus no dejo entrar ({r.status_code}): "\n                             "revisa el usuario y la clave de la conexion.")\n',
        '        except httpx.HTTPError as e:\n            raise NoResponde(f"Pegasus no contesto ({type(e).__name__}).")\n        if r.status_code == 429:\n            raise NoResponde(_mensaje_de_pausa(_pausar(r, self.sitio)))\n        if r.status_code != 200:\n            raise NoResponde(f"Pegasus no dejo entrar ({r.status_code}): "\n                             "revisa el usuario y la clave de la conexion.")\n')

cambiar('pegasus',
        '        self.http.headers["Authenticate"] = token\n\n    def _esperar(self) -> None:\n        hasta = pausa_hasta()\n        if hasta > time.time():\n            raise NoResponde(_mensaje_de_pausa(hasta))\n        falta = PAUSA - (time.monotonic() - self._ultima)\n',
        '        self.http.headers["Authenticate"] = token\n\n    def _esperar(self) -> None:\n        hasta = pausa_hasta(self.sitio)\n        if hasta > time.time():\n            raise NoResponde(_mensaje_de_pausa(hasta))\n        falta = PAUSA - (time.monotonic() - self._ultima)\n')

cambiar('pegasus',
        '            except httpx.HTTPError as e:\n                raise NoResponde(f"Pegasus no contesto ({type(e).__name__}).")\n            if r.status_code == 429:\n                raise NoResponde(_mensaje_de_pausa(_pausar(r)))\n            if r.status_code == 401 and intento == 1:\n                # La sesion vencio: una vez mas con una nueva.\n                _sesiones.pop((self.sitio, self._usuario), None)\n',
        '            except httpx.HTTPError as e:\n                raise NoResponde(f"Pegasus no contesto ({type(e).__name__}).")\n            if r.status_code == 429:\n                raise NoResponde(_mensaje_de_pausa(_pausar(r, self.sitio)))\n            if r.status_code == 401 and intento == 1:\n                # La sesion vencio: una vez mas con una nueva.\n                _sesiones.pop((self.sitio, self._usuario), None)\n')

cambiar('t_gps',
        '        return httpx.Response(429, headers={\n            "X-RateLimit-Reset": str(int(reloj_real.time()) + 120)})\n\n    conexion.quitar_pausa()\n    try:\n        cliente = conexion.Pegasus("https://cuota.invalid", "u", "c")\n        cliente.http = httpx.Client(transport=httpx.MockTransport(sitio))\n',
        '        return httpx.Response(429, headers={\n            "X-RateLimit-Reset": str(int(reloj_real.time()) + 120)})\n\n    conexion.quitar_pausa("https://cuota.invalid")\n    try:\n        cliente = conexion.Pegasus("https://cuota.invalid", "u", "c")\n        cliente.http = httpx.Client(transport=httpx.MockTransport(sitio))\n')

cambiar('t_gps',
        '        assert "bajar el ritmo" in r["error"]\n        assert len(llamadas) == antes\n    finally:\n        conexion.quitar_pausa()\n        conexion._sesiones.clear()\n\n\n',
        '        assert "bajar el ritmo" in r["error"]\n        assert len(llamadas) == antes\n    finally:\n        conexion.quitar_pausa("https://cuota.invalid")\n        conexion._sesiones.clear()\n\n\n')

cambiar('conftest',
        '# cada prueba. Aqui arriba se hace antes de que se importe nada.\nBASE_DE_PRUEBAS = "postgresql+psycopg://centauro:centauro_dev@db:5432/centauro_test"\nos.environ["DATABASE_URL"] = BASE_DE_PRUEBAS\n\nimport pytest  # noqa: E402\nfrom fastapi.testclient import TestClient  # noqa: E402\n',
        '# cada prueba. Aqui arriba se hace antes de que se importe nada.\nBASE_DE_PRUEBAS = "postgresql+psycopg://centauro:centauro_dev@db:5432/centauro_test"\nos.environ["DATABASE_URL"] = BASE_DE_PRUEBAS\n\n# Ni una prueba sale a Pegasus (seccion 60). Desde que se encendio la\n# lectura, el contenedor trae en su entorno el usuario de verdad, y una\n# prueba que llamo a la lectura sin su Pegasus de mentiras leyo el GPS\n# real --97 unidades, a la base de pruebas--. Las que necesitan un\n# Pegasus lo arman ellas; aqui se deja la conexion sin usuario.\nfor _variable in ("PEGASUS_SITIO", "PEGASUS_USUARIO", "PEGASUS_CLAVE",\n                  "PEGASUS_SECRETO_AVISO"):\n    os.environ[_variable] = ""\n\nimport pytest  # noqa: E402\nfrom fastapi.testclient import TestClient  # noqa: E402\n')

cambiar('bitacora',
        'cuántos: unidades, placas, eventos y tramos, sin nombres, placas ni\ncoordenadas.\n\n## 14. Lo que falta\n\n### Abierto\n',
        'cuántos: unidades, placas, eventos y tramos, sin nombres, placas ni\ncoordenadas.\n\n## 61. Todas las horas de la bitácora, del país del servicio\n\nDecisión de Salvador, 24 de septiembre: «tiene que salir con la hora del\npais. igual y poner una nota para que el personal sepa». Lo que tocó la\ncentral, las notas de turno y las alertas se guardan como un instante, y\nsalían con el reloj de la base: en UTC en desarrollo, y en hora de México\nen el servidor aunque el servicio fuera de Brasil. Las marcas ya iban con\nla hora del país. Ahora todo va con la hora de pared del país del\nservicio, y la bitácora lo dice arriba: «Todas las horas están en hora\nde Mexico».\n\nDe paso, los «?» que tocó el GPS dicen lo nuevo: el camino al punto (la\nunidad como testigo, «La unidad no ha salido» y de dónde salen las\ndistancias), «En curso» (la unidad no cuenta como reporte: un equipo\ncallado sigue en rojo aunque su camioneta se mueva) y la bitácora (una\nsola medida de la unidad por marca, y de qué país son las horas). El\nrecorrido de la primera vez ya trae Unidades para quien la ve, y el de\nMonitoreo dice que ahí cae lo que hay que atender ahora: un pánico, un\ninhibidor, un equipo callado.\n\nY las pruebas ya no pueden salir a Pegasus. Desde que se encendió la\nlectura, el contenedor trae el usuario de verdad en su entorno, y la\nprueba de «sin usuario no hace nada» leyó el GPS real —97 unidades, a la\nbase de pruebas— y falló. `conftest.py` deja la conexión sin usuario\nantes de importar nada, y la pausa por un 429 es de cada sitio: la de una\nprueba ya no puede borrar la del Pegasus de verdad.\n\n## 14. Lo que falta\n\n### Abierto\n')


# ============================================================ comprobar
def _md5(texto):
    return hashlib.md5(texto.encode("utf-8")).hexdigest()


distintos = [clave for clave in ARCHIVOS
             if _md5(textos[clave]) != ESPERADO[clave]]
distintos += [rel for rel, contenido in NUEVOS.items()
              if _md5(contenido) != ESPERADO["nuevo:" + rel]]
if distintos:
    raise SystemExit("Estos archivos no quedarian como los que se probaron: "
                     + ", ".join(distintos) + ". No se escribio nada.")

# ============================================================ escrituras
for clave, ruta in ARCHIVOS.items():
    actual = io.open(ruta, encoding="utf-8", newline="").read()
    if actual != textos[clave]:
        with io.open(ruta, "w", encoding="utf-8", newline="") as f:
            f.write(textos[clave])
        print("escrito  ", ruta.relative_to(RAIZ))
    else:
        print("sin cambio", ruta.relative_to(RAIZ))
for relativa, contenido in NUEVOS.items():
    ruta = B / relativa
    if ruta.exists() and io.open(ruta, encoding="utf-8", newline="").read() == contenido:
        print("sin cambio", ruta.relative_to(RAIZ))
    else:
        with io.open(ruta, "w", encoding="utf-8", newline="") as f:
            f.write(contenido)
        print("escrito  ", ruta.relative_to(RAIZ))
if saltados:
    print("ya estaban:", len(saltados), "cambios")
