"""Textos del task sheet en varios idiomas.

Por defecto va en ingles, porque el ejecutivo suele ser extranjero.
El consultor puede pedirlo en el idioma local cuando conviene.

Solo se traducen las etiquetas: los nombres, direcciones y la agenda
quedan como los captura el consultor.
"""

IDIOMAS = {"en": "English", "es": "Espanol", "pt": "Portugues"}
POR_DEFECTO = "en"

TEXTOS = {
    "en": {
        "confidential": "Confidential",
        "updated": "Updated",
        "linea": "Executive Protection",
        "open_map": "Open in Google Maps",
        "team": "Team",
        "executive": "Principal",
        "requested_by": "Requested by",
        "security_team": "Security team",
        "vehicle": "Security vehicle",
        "boards": "Boards",
        "origin": "Meet and greet",
        "origin_nota": "Start of service. Your team will be waiting here.",
        "flight": "Flight",
        "flight_arrival": "Arrival",
        "flight_departure": "Departure",
        "team_onsite": "Team on site",
        "before_flight": "min before the flight lands",
        "before_pickup": "min before the agreed time",
        "flight_from": "from",
        "days": "days",
        "schedule": "Schedule",
        "agenda": "Itinerary",
        "to_confirm": "TBC",
        "open_agenda": ("Open itinerary: to be defined during the service. "
                        "The team stays at your disposal from the "
                        "meet and greet point."),
        "hospitals": "Nearest hospitals",
        "lodging": "Accommodation (for reference)",
        "escalation": "In case of any issue",
        "embedded_service": "Embedded service",
        "coverage_sheet": "Coverage sheet",
        "covering": "Covering these days",
        "permanent_team": "Permanent team",
        "the_service": "The service",
        "fixed_point": "Fixed point (meet and greet)",
        "days_of_service": "Days of service",
        "report_time": "Report time",
        "operating_area": "Operating area",
        "geofence": "Geofence",
        "scope_block": "Agreements and scope",
        "agreements": "Agreements",
        "scope": "Scope of service",
        "service_coordination": "Service coordination",
        "contact_name": "Name",
        "phone": "Phone",
        "email": "Email",
        "protocol": "Service-specific protocol",
        "training": "Training and certifications",
        "valid_until": "Valid until",
        "rating": "rating",
        "principal": "Principal",
        "version": "Version",
        "footer_note": "Confidential document. For the client and the "
                       "assigned team only. Centauro, Executive Protection.",
        "added_today": "Added this day",
        "not_today": "Not covering this day",
        "extra_vehicle": "Additional vehicle",
        "vehicle_out": "Vehicle not assigned this day",
        "other_origin": "Different meeting point",
        "hospitals_from_hotel": "Distance from the hotel",
        "hospitals_from_encuentro": "Distance from the meeting point",
        "origin_tbc": "The driver confirms it with the principal the day before",
        "to_assign": "To be assigned",
        "no_hospitals": "No hospitals on file for this city",
        "armored": "Armored",
        "soft_skin": "Soft skin",
        "hours_at": "h of service at Centauro",
        "sign_title": "Identification sign",
        "sign_footer": "Your security team will display this sign.",
        "sign_look": "Please look for it on arrival.",
        "privacy": ("Confidential document. It contains security details and the "
                    "executive's movements. Do not share outside the authorized "
                    "personnel of this service."),
        "no_contacts": "No contacts",
        "dias_semana": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        "meses": ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        "modalidades": {"full_day": "full day", "medio_dia": "half day",
                        "transfer": "transfer"},
        "modalidades_plural": {"full_day": "full days", "medio_dia": "half days",
                               "transfer": "transfers"},
        "perfiles": {"Conductor de seguridad": "Security driver",
                     "Agente de seguridad": "Security agent",
                     "Coordinador de seguridad": "Security coordinator",
                     "Consultor de seguridad": "Security consultant"},
        "cargos": {"Consultor asignado": "Security consultant",
                   "Director de operaciones": "Operations director"},
    },
    "es": {
        "confidential": "Confidencial",
        "updated": "Actualizado",
        "linea": "Proteccion Ejecutiva",
        "open_map": "Ver en Google Maps",
        "team": "Equipo",
        "executive": "Ejecutivo principal",
        "requested_by": "Solicita",
        "security_team": "Equipo de seguridad",
        "vehicle": "Vehiculo de seguridad",
        "boards": "Aborda",
        "origin": "Meet and greet",
        "origin_nota": "Inicio del servicio. Aqui lo espera su equipo.",
        "flight": "Vuelo",
        "flight_arrival": "Llegada",
        "flight_departure": "Salida",
        "team_onsite": "Equipo en sitio",
        "before_flight": "min antes de que aterrice el vuelo",
        "before_pickup": "min antes de la hora acordada",
        "flight_from": "procedente de",
        "days": "dias",
        "schedule": "Programa",
        "agenda": "Agenda",
        "to_confirm": "Por confirmar",
        "open_agenda": ("Agenda abierta: se desarrolla durante el servicio. "
                        "El equipo permanece a su disposicion desde el "
                        "punto de encuentro."),
        "hospitals": "Hospitales cercanos",
        "lodging": "Hospedaje (informativo)",
        "escalation": "Ante cualquier anomalia",
        "embedded_service": "Servicio implantado",
        "coverage_sheet": "Hoja de cobertura",
        "covering": "Quien cubre estos dias",
        "permanent_team": "Equipo permanente",
        "the_service": "El servicio",
        "fixed_point": "Punto fijo (meet and greet)",
        "days_of_service": "Dias de servicio",
        "report_time": "Hora de presentacion",
        "operating_area": "Zona de operacion",
        "geofence": "Geocerca",
        "scope_block": "Acuerdos y alcance",
        "agreements": "Acuerdos",
        "scope": "Alcance del servicio",
        "service_coordination": "Coordinacion del servicio",
        "contact_name": "Nombre",
        "phone": "Telefono",
        "email": "Correo",
        "protocol": "Protocolo especial del servicio",
        "training": "Capacitacion y certificaciones",
        "valid_until": "Vigente hasta",
        "rating": "de calificacion",
        "principal": "Ejecutivo",
        "version": "Version",
        "footer_note": "Documento confidencial. Solo para el cliente y el "
                       "equipo asignado. Centauro, Proteccion Ejecutiva.",
        "added_today": "Se suma este dia",
        "not_today": "No cubre este dia",
        "extra_vehicle": "Unidad adicional",
        "vehicle_out": "Unidad que no va",
        "other_origin": "Otro punto de encuentro",
        "hospitals_from_hotel": "Distancia desde el hotel",
        "hospitals_from_encuentro": "Distancia desde el punto de encuentro",
        "origin_tbc": "El conductor lo confirma con el ejecutivo un dia antes",
        "to_assign": "Por asignar",
        "no_hospitals": "Sin hospitales cargados para esta ciudad",
        "armored": "Blindada",
        "soft_skin": "Soft skin",
        "hours_at": "h de servicio en Centauro",
        "sign_title": "Senal de identificacion",
        "sign_footer": "Su equipo de seguridad mostrara esta senal.",
        "sign_look": "Busquela al salir.",
        "privacy": ("Documento confidencial. Contiene datos de seguridad y "
                    "movimientos del ejecutivo. No compartir fuera de las "
                    "personas autorizadas del servicio."),
        "no_contacts": "Sin contactos",
        "dias_semana": ["Lun", "Mar", "Mie", "Jue", "Vie", "Sab", "Dom"],
        "meses": ["ene", "feb", "mar", "abr", "may", "jun",
                  "jul", "ago", "sep", "oct", "nov", "dic"],
        "modalidades": {"full_day": "dia completo", "medio_dia": "medio dia",
                        "transfer": "transfer"},
        "modalidades_plural": {"full_day": "dias completos",
                               "medio_dia": "medios dias",
                               "transfer": "transfers"},
        "perfiles": {},
        "cargos": {"Consultor asignado": "Consultor de seguridad"},
    },
    "pt": {
        "confidential": "Confidencial",
        "updated": "Atualizado",
        "linea": "Protecao Executiva",
        "open_map": "Ver no Google Maps",
        "team": "Equipe",
        "executive": "Executivo principal",
        "requested_by": "Solicitante",
        "security_team": "Equipe de seguranca",
        "vehicle": "Veiculo de seguranca",
        "boards": "Embarca",
        "origin": "Meet and greet",
        "origin_nota": "Inicio do servico. Aqui a equipe o aguarda.",
        "flight": "Voo",
        "flight_arrival": "Chegada",
        "flight_departure": "Saida",
        "team_onsite": "Equipe no local",
        "before_flight": "min antes de o voo aterrissar",
        "before_pickup": "min antes do horario combinado",
        "flight_from": "procedente de",
        "days": "dias",
        "schedule": "Programa",
        "agenda": "Agenda",
        "to_confirm": "A confirmar",
        "open_agenda": ("Agenda aberta: definida durante o servico. A equipe "
                        "permanece a sua disposicao a partir do ponto de "
                        "encontro."),
        "hospitals": "Hospitais proximos",
        "lodging": "Hospedagem (informativo)",
        "escalation": "Em caso de qualquer anomalia",
        "embedded_service": "Servico implantado",
        "coverage_sheet": "Folha de cobertura",
        "covering": "Quem cobre estes dias",
        "permanent_team": "Equipe permanente",
        "the_service": "O servico",
        "fixed_point": "Ponto fixo (meet and greet)",
        "days_of_service": "Dias de servico",
        "report_time": "Hora de apresentacao",
        "operating_area": "Zona de operacao",
        "geofence": "Geocerca",
        "scope_block": "Acordos e alcance",
        "agreements": "Acordos",
        "scope": "Alcance do servico",
        "service_coordination": "Coordenacao do servico",
        "contact_name": "Nome",
        "phone": "Telefone",
        "email": "E-mail",
        "protocol": "Protocolo especial do servico",
        "training": "Capacitacao e certificacoes",
        "valid_until": "Valido ate",
        "rating": "de avaliacao",
        "principal": "Executivo",
        "version": "Versao",
        "footer_note": "Documento confidencial. Apenas para o cliente e a "
                       "equipe designada. Centauro, Protecao Executiva.",
        "added_today": "Entra neste dia",
        "not_today": "Nao cobre este dia",
        "extra_vehicle": "Veiculo adicional",
        "vehicle_out": "Veiculo que nao vai",
        "other_origin": "Outro ponto de encontro",
        "hospitals_from_hotel": "Distancia a partir do hotel",
        "hospitals_from_encuentro": "Distancia a partir do ponto de encontro",
        "origin_tbc": "O motorista confirma com o executivo na vespera",
        "to_assign": "A definir",
        "no_hospitals": "Sem hospitais cadastrados para esta cidade",
        "armored": "Blindado",
        "soft_skin": "Soft skin",
        "hours_at": "h de servico na Centauro",
        "sign_title": "Sinal de identificacao",
        "sign_footer": "Sua equipe de seguranca mostrara este sinal.",
        "sign_look": "Procure por ele na chegada.",
        "privacy": ("Documento confidencial. Contem dados de seguranca e "
                    "movimentos do executivo. Nao compartilhar fora das pessoas "
                    "autorizadas do servico."),
        "no_contacts": "Sem contatos",
        "dias_semana": ["Seg", "Ter", "Qua", "Qui", "Sex", "Sab", "Dom"],
        "meses": ["jan", "fev", "mar", "abr", "mai", "jun",
                  "jul", "ago", "set", "out", "nov", "dez"],
        "modalidades": {"full_day": "dia completo", "medio_dia": "meio dia",
                        "transfer": "transfer"},
        "modalidades_plural": {"full_day": "dias completos",
                               "medio_dia": "meios dias",
                               "transfer": "transfers"},
        "perfiles": {"Conductor de seguridad": "Motorista de seguranca",
                     "Agente de seguridad": "Agente de seguranca",
                     "Coordinador de seguridad": "Coordenador de seguranca",
                     "Consultor de seguridad": "Consultor de seguranca"},
        "cargos": {"Consultor asignado": "Consultor de seguranca",
                   "Director de operaciones": "Diretor de operacoes"},
    },
}


def diccionario(idioma: str | None) -> dict:
    return TEXTOS.get((idioma or POR_DEFECTO).lower(), TEXTOS[POR_DEFECTO])


def fecha_larga(iso: str, t: dict) -> str:
    """05 Oct 2026, sin ambiguedad entre formatos de fecha."""
    from datetime import date
    f = date.fromisoformat(iso)
    return f"{f.day:02d} {t['meses'][f.month - 1]} {f.year}"
