"""Textos del task sheet en varios idiomas.

Por defecto va en ingles, porque el ejecutivo suele ser extranjero.
El consultor puede pedirlo en el idioma local cuando conviene.

Solo se traducen las etiquetas: los nombres, direcciones y la agenda
quedan como los captura el consultor.
"""

IDIOMAS = {"en": "English", "es": "Español", "pt": "Português"}
POR_DEFECTO = "en"

TEXTOS = {
    "en": {
        "confidential": "Confidential",
        "updated": "Updated",
        "linea": "Executive Protection",
        "open_map": "Open in Google Maps",
        "team": "Team",
        "executive": "Principal",
        "requested_by": "Requested by",
        "security_team": "Security team",
        "vehicle": "Security vehicle",
        "boards": "Boards",
        "origin": "Meet and greet",
        "origin_nota": "Start of service. Your team will be waiting here.",
        "flight": "Flight",
        "flight_arrival": "Arrival",
        "flight_departure": "Departure",
        "team_onsite": "Team on site",
        "before_flight": "min before the flight lands",
        "before_pickup": "min before the agreed time",
        "flight_from": "from",
        "days": "days",
        "schedule": "Schedule",
        "agenda": "Itinerary",
        "to_confirm": "TBC",
        "open_agenda": ("Open itinerary: to be defined during the service. "
                        "The team stays at your disposal from the "
                        "meet and greet point."),
        "hospitals": "Nearest hospitals",
        "lodging": "Accommodation (for reference)",
        "escalation": "In case of any issue",
        "embedded_service": "Embedded service",
        "coverage_sheet": "Coverage sheet",
        "covering": "Covering these days",
        "permanent_team": "Permanent team",
        "the_service": "The service",
        "fixed_point": "Fixed point (meet and greet)",
        "days_of_service": "Days of service",
        "report_time": "Report time",
        "operating_area": "Operating area",
        "geofence": "Geofence",
        "scope_block": "Agreements and scope",
        "agreements": "Agreements",
        "scope": "Scope of service",
        "service_coordination": "Service coordination",
        "contact_name": "Name",
        "phone": "Phone",
        "email": "Email",
        "protocol": "Service-specific protocol",
        "training": "Training and certifications",
        "valid_until": "Valid until",
        "rating": "rating",
        "principal": "Principal",
        "version": "Version",
        "footer_note": "Confidential document. For the client and the "
                       "assigned team only. Centauro, Executive Protection.",
        "added_today": "Added this day",
        "not_today": "Not covering this day",
        "extra_vehicle": "Additional vehicle",
        "vehicle_out": "Vehicle not assigned this day",
        "other_origin": "Different meeting point",
        "hospitals_from_hotel": "Distance from the hotel",
        "hospitals_from_encuentro": "Distance from the meeting point",
        "origin_tbc": "The driver confirms it with the principal the day before",
        "to_assign": "To be assigned",
        "no_hospitals": "No hospitals on file for this city",
        "armored": "Armored",
        "soft_skin": "Soft skin",
        "hours_at": "h of service at Centauro",
        "sign_title": "Identification sign",
        "sign_footer": "Your security team will display this sign.",
        "sign_look": "Please look for it on arrival.",
        "privacy": ("Confidential document. It contains security details and the "
                    "executive's movements. Do not share outside the authorized "
                    "personnel of this service."),
        "no_contacts": "No contacts",
        "dias_semana": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        "meses": ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        "modalidades": {"full_day": "full day", "medio_dia": "half day",
                        "transfer": "transfer"},
        "modalidades_plural": {"full_day": "full days", "medio_dia": "half days",
                               "transfer": "transfers"},
        "perfiles": {"Conductor de seguridad": "Security driver",
                     "Agente de seguridad": "Security agent",
                     "Coordinador de seguridad": "Security coordinator",
                     "Consultor de seguridad": "Security consultant"},
        "cargos": {"Consultor asignado": "Security consultant",
                   "Director de operaciones": "Operations director"},
    },
    "es": {
        "confidential": "Confidencial",
        "updated": "Actualizado",
        "linea": "Protección Ejecutiva",
        "open_map": "Ver en Google Maps",
        "team": "Equipo",
        "executive": "Ejecutivo principal",
        "requested_by": "Solicita",
        "security_team": "Equipo de seguridad",
        "vehicle": "Vehículo de seguridad",
        "boards": "Aborda",
        "origin": "Meet and greet",
        "origin_nota": "Inicio del servicio. Aquí lo espera su equipo.",
        "flight": "Vuelo",
        "flight_arrival": "Llegada",
        "flight_departure": "Salida",
        "team_onsite": "Equipo en sitio",
        "before_flight": "min antes de que aterrice el vuelo",
        "before_pickup": "min antes de la hora acordada",
        "flight_from": "procedente de",
        "days": "días",
        "schedule": "Programa",
        "agenda": "Agenda",
        "to_confirm": "Por confirmar",
        "open_agenda": ("Agenda abierta: se desarrolla durante el servicio. "
                        "El equipo permanece a su disposición desde el "
                        "punto de encuentro."),
        "hospitals": "Hospitales cercanos",
        "lodging": "Hospedaje (informativo)",
        "escalation": "Ante cualquier anomalía",
        "embedded_service": "Servicio implantado",
        "coverage_sheet": "Hoja de cobertura",
        "covering": "Quién cubre estos días",
        "permanent_team": "Equipo permanente",
        "the_service": "El servicio",
        "fixed_point": "Punto fijo (meet and greet)",
        "days_of_service": "Días de servicio",
        "report_time": "Hora de presentación",
        "operating_area": "Zona de operación",
        "geofence": "Geocerca",
        "scope_block": "Acuerdos y alcance",
        "agreements": "Acuerdos",
        "scope": "Alcance del servicio",
        "service_coordination": "Coordinación del servicio",
        "contact_name": "Nombre",
        "phone": "Teléfono",
        "email": "Correo",
        "protocol": "Protocolo especial del servicio",
        "training": "Capacitación y certificaciones",
        "valid_until": "Vigente hasta",
        "rating": "de calificación",
        "principal": "Ejecutivo",
        "version": "Versión",
        "footer_note": "Documento confidencial. Solo para el cliente y el "
                       "equipo asignado. Centauro, Protección Ejecutiva.",
        "added_today": "Se suma este día",
        "not_today": "No cubre este día",
        "extra_vehicle": "Unidad adicional",
        "vehicle_out": "Unidad que no va",
        "other_origin": "Otro punto de encuentro",
        "hospitals_from_hotel": "Distancia desde el hotel",
        "hospitals_from_encuentro": "Distancia desde el punto de encuentro",
        "origin_tbc": "El conductor lo confirma con el ejecutivo un día antes",
        "to_assign": "Por asignar",
        "no_hospitals": "Sin hospitales cargados para esta ciudad",
        "armored": "Blindada",
        "soft_skin": "Soft skin",
        "hours_at": "h de servicio en Centauro",
        "sign_title": "Señal de identificación",
        "sign_footer": "Su equipo de seguridad mostrará esta señal.",
        "sign_look": "Búsquela al salir.",
        "privacy": ("Documento confidencial. Contiene datos de seguridad y "
                    "movimientos del ejecutivo. No compartir fuera de las "
                    "personas autorizadas del servicio."),
        "no_contacts": "Sin contactos",
        "dias_semana": ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"],
        "meses": ["ene", "feb", "mar", "abr", "may", "jun",
                  "jul", "ago", "sep", "oct", "nov", "dic"],
        "modalidades": {"full_day": "día completo", "medio_dia": "medio día",
                        "transfer": "transfer"},
        "modalidades_plural": {"full_day": "días completos",
                               "medio_dia": "medios días",
                               "transfer": "transfers"},
        "perfiles": {},
        "cargos": {"Consultor asignado": "Consultor de seguridad"},
    },
    "pt": {
        "confidential": "Confidencial",
        "updated": "Atualizado",
        "linea": "Proteção Executiva",
        "open_map": "Ver no Google Maps",
        "team": "Equipe",
        "executive": "Executivo principal",
        "requested_by": "Solicitante",
        "security_team": "Equipe de segurança",
        "vehicle": "Veículo de segurança",
        "boards": "Embarca",
        "origin": "Meet and greet",
        "origin_nota": "Início do serviço. Aqui a equipe o aguarda.",
        "flight": "Voo",
        "flight_arrival": "Chegada",
        "flight_departure": "Saída",
        "team_onsite": "Equipe no local",
        "before_flight": "min antes de o voo aterrissar",
        "before_pickup": "min antes do horário combinado",
        "flight_from": "procedente de",
        "days": "dias",
        "schedule": "Programa",
        "agenda": "Agenda",
        "to_confirm": "A confirmar",
        "open_agenda": ("Agenda aberta: definida durante o serviço. A equipe "
                        "permanece à sua disposição a partir do ponto de "
                        "encontro."),
        "hospitals": "Hospitais próximos",
        "lodging": "Hospedagem (informativo)",
        "escalation": "Em caso de qualquer anomalia",
        "embedded_service": "Serviço implantado",
        "coverage_sheet": "Folha de cobertura",
        "covering": "Quem cobre estes dias",
        "permanent_team": "Equipe permanente",
        "the_service": "O serviço",
        "fixed_point": "Ponto fixo (meet and greet)",
        "days_of_service": "Dias de serviço",
        "report_time": "Hora de apresentação",
        "operating_area": "Zona de operação",
        "geofence": "Geocerca",
        "scope_block": "Acordos e alcance",
        "agreements": "Acordos",
        "scope": "Alcance do serviço",
        "service_coordination": "Coordenação do serviço",
        "contact_name": "Nome",
        "phone": "Telefone",
        "email": "E-mail",
        "protocol": "Protocolo especial do serviço",
        "training": "Capacitação e certificações",
        "valid_until": "Válido até",
        "rating": "de avaliação",
        "principal": "Executivo",
        "version": "Versão",
        "footer_note": "Documento confidencial. Apenas para o cliente e a "
                       "equipe designada. Centauro, Proteção Executiva.",
        "added_today": "Entra neste dia",
        "not_today": "Não cobre este dia",
        "extra_vehicle": "Veículo adicional",
        "vehicle_out": "Veículo que não vai",
        "other_origin": "Outro ponto de encontro",
        "hospitals_from_hotel": "Distância a partir do hotel",
        "hospitals_from_encuentro": "Distância a partir do ponto de encontro",
        "origin_tbc": "O motorista confirma com o executivo na véspera",
        "to_assign": "A definir",
        "no_hospitals": "Sem hospitais cadastrados para esta cidade",
        "armored": "Blindado",
        "soft_skin": "Soft skin",
        "hours_at": "h de serviço na Centauro",
        "sign_title": "Sinal de identificação",
        "sign_footer": "Sua equipe de segurança mostrará este sinal.",
        "sign_look": "Procure por ele na chegada.",
        "privacy": ("Documento confidencial. Contém dados de segurança e "
                    "movimentos do executivo. Não compartilhar fora das pessoas "
                    "autorizadas do serviço."),
        "no_contacts": "Sem contatos",
        "dias_semana": ["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"],
        "meses": ["jan", "fev", "mar", "abr", "mai", "jun",
                  "jul", "ago", "set", "out", "nov", "dez"],
        "modalidades": {"full_day": "dia completo", "medio_dia": "meio dia",
                        "transfer": "transfer"},
        "modalidades_plural": {"full_day": "dias completos",
                               "medio_dia": "meios dias",
                               "transfer": "transfers"},
        "perfiles": {"Conductor de seguridad": "Motorista de segurança",
                     "Agente de seguridad": "Agente de segurança",
                     "Coordinador de seguridad": "Coordenador de segurança",
                     "Consultor de seguridad": "Consultor de segurança"},
        "cargos": {"Consultor asignado": "Consultor de segurança",
                   "Director de operaciones": "Diretor de operações"},
    },
}


def diccionario(idioma: str | None) -> dict:
    return TEXTOS.get((idioma or POR_DEFECTO).lower(), TEXTOS[POR_DEFECTO])


def fecha_larga(iso: str, t: dict) -> str:
    """05 Oct 2026, sin ambiguedad entre formatos de fecha."""
    from datetime import date
    f = date.fromisoformat(iso)
    return f"{f.day:02d} {t['meses'][f.month - 1]} {f.year}"
