"""esquema inicial

Revision ID: 03a2181c86e9
Revises: 
Create Date: 2026-09-12 04:35:50.738512
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '03a2181c86e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('blindado', sa.Boolean(), nullable=False),
    sa.Column('rendimiento_km_litro', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('moneda_local', sa.Enum('MXN', 'BRL', 'USD', 'VES', name='moneda'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('perfil_personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('modalidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Enum('FULL_DAY', 'MEDIO_DIA', 'TRANSFER', name='codigomodalidad'), nullable=False),
    sa.Column('horas', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('horas_descanso', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('aplica_horas_extra', sa.Boolean(), nullable=False),
    sa.Column('bloquea_dia_completo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pais_id', 'codigo')
    )
    op.create_table('parametro_combustible',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('precio_litro', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('holgura_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plaza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('tiene_recurso_local', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pais_id', 'nombre')
    )
    op.create_table('tabulador_viatico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.Enum('ALIMENTOS', 'HOSPEDAJE', 'COMBUSTIBLE', 'CASETAS', 'TRASLADO_PERSONAL', 'OTROS', name='conceptoviatico'), nullable=False),
    sa.Column('escenario', sa.Enum('FULL_DAY_LOCAL', 'FULL_DAY_FORANEO', 'MEDIO_DIA', 'TRANSFER', name='escenarioviatico'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_abierto', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pais_id', 'concepto', 'escenario')
    )
    op.create_table('tarifario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('moneda', sa.Enum('MXN', 'BRL', 'USD', 'VES', name='moneda'), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('tarifario_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.ForeignKeyConstraint(['tarifario_id'], ['tarifario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odoo_id')
    )
    op.create_table('comision_personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('modalidad_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_hora_extra', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('moneda', sa.Enum('MXN', 'BRL', 'USD', 'VES', name='moneda'), nullable=False),
    sa.ForeignKeyConstraint(['modalidad_id'], ['modalidad.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_personal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pais_id', 'perfil_id', 'modalidad_id')
    )
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('correo', sa.String(length=160), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('plaza_id', sa.Integer(), nullable=False),
    sa.Column('es_freelance', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_personal.id'], ),
    sa.ForeignKeyConstraint(['plaza_id'], ['plaza.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('odoo_id')
    )
    op.create_table('tarifa_recurso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarifario_id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('modalidad_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_hora_extra', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['modalidad_id'], ['modalidad.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_personal.id'], ),
    sa.ForeignKeyConstraint(['tarifario_id'], ['tarifario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tarifario_id', 'perfil_id', 'modalidad_id')
    )
    op.create_table('tarifa_vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarifario_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('modalidad_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_mensual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_vehiculo.id'], ),
    sa.ForeignKeyConstraint(['modalidad_id'], ['modalidad.id'], ),
    sa.ForeignKeyConstraint(['tarifario_id'], ['tarifario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tarifario_id', 'categoria_id', 'modalidad_id')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('plaza_id', sa.Integer(), nullable=False),
    sa.Column('costo_diario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_vehiculo.id'], ),
    sa.ForeignKeyConstraint(['plaza_id'], ['plaza.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=24), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('plaza_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('EVENTUAL', 'IMPLANTADO', name='tiposervicio'), nullable=False),
    sa.Column('estatus', sa.Enum('BORRADOR', 'COTIZADO', 'AUTORIZADO', 'PLANEADO', 'EN_CURSO', 'TERMINADO', 'CERRADO', 'CANCELADO', name='estatusservicio'), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=True),
    sa.Column('solicitante_nombre', sa.String(length=160), nullable=True),
    sa.Column('solicitante_correo', sa.String(length=160), nullable=True),
    sa.Column('ejecutivo_nombre', sa.String(length=160), nullable=True),
    sa.Column('ejecutivo_correo', sa.String(length=160), nullable=True),
    sa.Column('servicio_origen_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['consultor_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.ForeignKeyConstraint(['plaza_id'], ['plaza.id'], ),
    sa.ForeignKeyConstraint(['servicio_origen_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('tarifa_freelance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('modalidad_id', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo_hora_extra', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('moneda', sa.Enum('MXN', 'BRL', 'USD', 'VES', name='moneda'), nullable=False),
    sa.ForeignKeyConstraint(['modalidad_id'], ['modalidad.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'modalidad_id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=160), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=200), nullable=True),
    sa.Column('rol', sa.Enum('PERSONAL_SEGURIDAD', 'CENTRAL', 'CONSULTOR', 'DIRECTOR_OPERACIONES', 'DIRECTOR_GENERAL', 'FINANZAS', 'ADMIN', name='rol'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=80), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('usado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitacion_token'), 'invitacion', ['token'], unique=True)
    op.create_table('jornada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('modalidad_id', sa.Integer(), nullable=False),
    sa.Column('inicio_programado', sa.DateTime(), nullable=False),
    sa.Column('fin_programado', sa.DateTime(), nullable=False),
    sa.Column('es_foraneo', sa.Boolean(), nullable=False),
    sa.Column('km_estimados', sa.Integer(), nullable=True),
    sa.Column('estatus', sa.Enum('PLANEADA', 'CONFIRMADA', 'PROXIMA_A_INICIAR', 'EN_CURSO', 'TERMINADA', 'CANCELADA', name='estatusjornada'), nullable=False),
    sa.Column('origen_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('origen_lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('geocerca_metros', sa.Integer(), nullable=False),
    sa.Column('origen_direccion', sa.String(length=300), nullable=True),
    sa.Column('inicio_real', sa.DateTime(), nullable=True),
    sa.Column('fin_real', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['modalidad_id'], ['modalidad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo_id', 'fecha')
    )
    op.create_table('alerta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('FUERA_DE_GEOCERCA', 'FUERA_DE_VENTANA', 'SIN_REPORTE', 'HORAS_EXTRA_PROXIMAS', 'RECURSO_SIN_CONFIRMAR', 'VIATICO_NO_TRANSFERIDO', 'VEHICULO_SIN_ASIGNAR', name='tipoalerta'), nullable=False),
    sa.Column('mensaje', sa.String(length=400), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atendida', sa.Boolean(), nullable=False),
    sa.Column('atendida_por_id', sa.Integer(), nullable=True),
    sa.Column('resolucion', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['atendida_por_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignacion_personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('reemplaza_a_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['reemplaza_a_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jornada_id', 'persona_id')
    )
    op.create_table('asignacion_vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jornada_id', 'vehiculo_id')
    )
    op.create_table('asignacion_viatico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('escenario', sa.Enum('FULL_DAY_LOCAL', 'FULL_DAY_FORANEO', 'MEDIO_DIA', 'TRANSFER', name='escenarioviatico'), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_comprobado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_devuelto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('MXN', 'BRL', 'USD', 'VES', name='moneda'), nullable=False),
    sa.Column('estatus', sa.Enum('ASIGNADO', 'SOLICITADO', 'TRANSFERIDO', 'EN_COMPROBACION', 'CERRADO', 'DEVUELTO', name='estatusviatico'), nullable=False),
    sa.Column('asignado_por_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('limite_comprobacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jornada_id', 'persona_id')
    )
    op.create_table('hito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('LLEGADA_ORIGEN', 'CONTACTO_EJECUTIVO', 'LLEGADA_DESTINO', 'SALIDA_RUTA', 'STANDBY', 'FIN_SERVICIO', name='tipohito'), nullable=False),
    sa.Column('marcado_en', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('distancia_origen_m', sa.Integer(), nullable=True),
    sa.Column('dentro_geocerca', sa.Boolean(), nullable=True),
    sa.Column('fuera_de_ventana', sa.Boolean(), nullable=False),
    sa.Column('requiere_revision', sa.Boolean(), nullable=False),
    sa.Column('nota', sa.String(length=300), nullable=True),
    sa.Column('ajustado_por_id', sa.Integer(), nullable=True),
    sa.Column('marcado_original', sa.DateTime(), nullable=True),
    sa.Column('justificacion_ajuste', sa.String(length=400), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ajustado_por_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('destinatario', sa.Enum('SOLICITANTE', 'EJECUTIVO', 'CENTRAL', 'CONSULTOR', 'PERSONAL', name='destinatario'), nullable=False),
    sa.Column('canal', sa.Enum('CORREO', 'WHATSAPP', 'AMBOS', 'APP', name='canal'), nullable=False),
    sa.Column('correo', sa.String(length=160), nullable=True),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('cuerpo', sa.String(length=2000), nullable=False),
    sa.Column('enlace_seguimiento', sa.String(length=400), nullable=True),
    sa.Column('expira_en', sa.DateTime(), nullable=True),
    sa.Column('enviada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_accion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('PERSONAL_SEGURIDAD', 'CENTRAL', 'CONSULTOR', 'DIRECTOR_OPERACIONES', 'DIRECTOR_GENERAL', 'FINANZAS', 'ADMIN', name='rol'), nullable=False),
    sa.Column('accion', sa.String(length=80), nullable=False),
    sa.Column('detalle', sa.String(length=400), nullable=True),
    sa.Column('en_cobertura', sa.Boolean(), nullable=False),
    sa.Column('titular_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.ForeignKeyConstraint(['titular_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comprobante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.Enum('ALIMENTOS', 'HOSPEDAJE', 'COMBUSTIBLE', 'CASETAS', 'TRASLADO_PERSONAL', 'OTROS', name='conceptoviatico'), nullable=False),
    sa.Column('tipo', sa.Enum('FACTURA', 'NOTA', name='tipocomprobante'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('archivo_url', sa.String(length=400), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.Column('observacion', sa.String(length=300), nullable=True),
    sa.Column('subido_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignacion_viatico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepto_asignado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.Enum('ALIMENTOS', 'HOSPEDAJE', 'COMBUSTIBLE', 'CASETAS', 'TRASLADO_PERSONAL', 'OTROS', name='conceptoviatico'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('origen', sa.Enum('TABULADOR', 'ESTIMADO', 'MANUAL', name='origenmonto'), nullable=False),
    sa.Column('es_adicional', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignacion_viatico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud_transferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('MXN', 'BRL', 'USD', 'VES', name='moneda'), nullable=False),
    sa.Column('estatus', sa.Enum('PENDIENTE', 'ENVIADA', 'CONFIRMADA', 'CANCELADA', name='estatustransferencia'), nullable=False),
    sa.Column('lote', sa.String(length=40), nullable=True),
    sa.Column('referencia_odoo', sa.String(length=80), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enviada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignacion_viatico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud_transferencia')
    op.drop_table('concepto_asignado')
    op.drop_table('comprobante')
    op.drop_table('registro_accion')
    op.drop_table('notificacion')
    op.drop_table('hito')
    op.drop_table('asignacion_viatico')
    op.drop_table('asignacion_vehiculo')
    op.drop_table('asignacion_personal')
    op.drop_table('alerta')
    op.drop_table('jornada')
    op.drop_index(op.f('ix_invitacion_token'), table_name='invitacion')
    op.drop_table('invitacion')
    op.drop_table('equipo')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('tarifa_freelance')
    op.drop_table('servicio')
    op.drop_table('vehiculo')
    op.drop_table('tarifa_vehiculo')
    op.drop_table('tarifa_recurso')
    op.drop_table('persona')
    op.drop_table('comision_personal')
    op.drop_table('cliente')
    op.drop_table('tarifario')
    op.drop_table('tabulador_viatico')
    op.drop_table('plaza')
    op.drop_table('parametro_combustible')
    op.drop_table('modalidad')
    op.drop_table('perfil_personal')
    op.drop_table('pais')
    op.drop_table('categoria_vehiculo')
    # ### end Alembic commands ###
