"""telefonos y senal de identificacion

Revision ID: 19a52685f77e
Revises: 59ccc368e289
Create Date: 2026-09-12 05:52:37.764577
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '19a52685f77e'
down_revision: Union[str, None] = '59ccc368e289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('solicitante_telefono', sa.String(length=40), nullable=True))
    op.add_column('servicio', sa.Column('ejecutivo_telefono', sa.String(length=40), nullable=True))
    op.add_column('servicio', sa.Column('senal_texto', sa.String(length=80), nullable=True))
    op.add_column('servicio', sa.Column('senal_imagen', sa.Text(), nullable=True))
    op.add_column('servicio', sa.Column('senal_nota', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicio', 'senal_nota')
    op.drop_column('servicio', 'senal_imagen')
    op.drop_column('servicio', 'senal_texto')
    op.drop_column('servicio', 'ejecutivo_telefono')
    op.drop_column('servicio', 'solicitante_telefono')
    # ### end Alembic commands ###
