"""task sheet hospitales y hoteles

Revision ID: 29ecac30d1f2
Revises: 6d1b2bc773f7
Create Date: 2026-09-12 05:36:36.341827
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '29ecac30d1f2'
down_revision: Union[str, None] = '6d1b2bc773f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
