"""criterio no aplicable

Revision ID: 34866cf81f77
Revises: a520cb8cc432
Create Date: 2026-09-12 05:09:59.169250
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '34866cf81f77'
down_revision: Union[str, None] = 'a520cb8cc432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultado_criterio', sa.Column('aplica', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resultado_criterio', 'aplica')
    # ### end Alembic commands ###
