"""folio AI-S y alias de equipo

Revision ID: 59ccc368e289
Revises: 29ecac30d1f2
Create Date: 2026-09-12 05:44:58.237938
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '59ccc368e289'
down_revision: Union[str, None] = '29ecac30d1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipo', sa.Column('alias', sa.String(length=20), server_default='Alfa', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipo', 'alias')
    # ### end Alembic commands ###
