"""task sheet hospitales y hoteles

Revision ID: 6d1b2bc773f7
Revises: 34866cf81f77
Create Date: 2026-09-12 05:33:24.304345
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d1b2bc773f7'
down_revision: Union[str, None] = '34866cf81f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('plaza_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('nivel_atencion', sa.String(length=60), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.ForeignKeyConstraint(['plaza_id'], ['plaza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('plaza_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.ForeignKeyConstraint(['plaza_id'], ['plaza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospedaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('nombre_libre', sa.String(length=160), nullable=True),
    sa.Column('direccion_libre', sa.String(length=300), nullable=True),
    sa.Column('telefono_libre', sa.String(length=40), nullable=True),
    sa.Column('habitacion', sa.String(length=40), nullable=True),
    sa.Column('desde', sa.Date(), nullable=False),
    sa.Column('hasta', sa.Date(), nullable=False),
    sa.Column('notas', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.Enum('BORRADOR', 'PUBLICADO', name='estatustasksheet'), nullable=False),
    sa.Column('contenido', sa.String(length=20000), nullable=False),
    sa.Column('motivo_cambio', sa.String(length=300), nullable=True),
    sa.Column('publicado_por_id', sa.Integer(), nullable=True),
    sa.Column('publicado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publicado_por_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id', 'version')
    )
    op.create_table('agenda_jornada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('resumen', sa.String(length=300), nullable=True),
    sa.Column('puntos', sa.String(length=2000), nullable=True),
    sa.Column('archivo_url', sa.String(length=400), nullable=True),
    sa.Column('cargada_por_id', sa.Integer(), nullable=False),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargada_por_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jornada_id')
    )
    op.add_column('persona', sa.Column('telefono', sa.String(length=40), nullable=True))
    op.add_column('persona', sa.Column('foto_url', sa.String(length=400), nullable=True))
    op.add_column('vehiculo', sa.Column('color', sa.String(length=40), nullable=True))
    op.add_column('vehiculo', sa.Column('modelo_anio', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculo', 'modelo_anio')
    op.drop_column('vehiculo', 'color')
    op.drop_column('persona', 'foto_url')
    op.drop_column('persona', 'telefono')
    op.drop_table('agenda_jornada')
    op.drop_table('task_sheet')
    op.drop_table('hospedaje')
    op.drop_table('hotel')
    op.drop_table('hospital')
    # ### end Alembic commands ###
