"""bonos estrellas y comisiones

Revision ID: a520cb8cc432
Revises: fe78fc203ee6
Create Date: 2026-09-12 05:07:23.017303
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a520cb8cc432'
down_revision: Union[str, None] = 'fe78fc203ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criterio_estrella',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Enum('PUNTUALIDAD', 'SEGUIMIENTO_APP', 'CAPACITACION', 'CIERRE_VIATICOS', name='codigocriterio'), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('umbral_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monto_mensual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('MXN', 'BRL', 'USD', 'VES', name='moneda'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pais_id', 'codigo')
    )
    op.create_table('dia_festivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('factor_comision', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pais_id', 'fecha')
    )
    op.create_index(op.f('ix_dia_festivo_fecha'), 'dia_festivo', ['fecha'], unique=False)
    op.create_table('porcentaje_comision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio', sa.Enum('EVENTUAL', 'IMPLANTADO', name='tiposervicio'), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pais_id', 'tipo_servicio')
    )
    op.create_table('comision_consultor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('facturacion', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('viaticos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('MXN', 'BRL', 'USD', 'VES', name='moneda'), nullable=False),
    sa.Column('estatus', sa.Enum('GENERADA', 'RETENIDA', 'PAGADA', 'PERDIDA', 'AJUSTADA', name='estatuscomision'), nullable=False),
    sa.Column('motivo', sa.String(length=400), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultor_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id', 'consultor_id')
    )
    op.create_table('ajuste_comision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comision_id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=400), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comision_id'], ['comision_consultor.id'], ),
    sa.ForeignKeyConstraint(['consultor_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('jornada_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('gravedad', sa.Enum('ERROR_MENOR', 'LEVE', 'GRAVE', name='gravedadincidencia'), nullable=False),
    sa.Column('descripcion', sa.String(length=600), nullable=False),
    sa.Column('clasificada_por_id', sa.Integer(), nullable=False),
    sa.Column('visto_bueno_por_id', sa.Integer(), nullable=True),
    sa.Column('autorizada', sa.Boolean(), nullable=False),
    sa.Column('resolucion_direccion', sa.String(length=600), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clasificada_por_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.ForeignKeyConstraint(['visto_bueno_por_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidencia_fecha'), 'incidencia', ['fecha'], unique=False)
    op.create_table('evaluacion_mensual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('jornadas_evaluadas', sa.Integer(), nullable=False),
    sa.Column('estrellas', sa.Integer(), nullable=False),
    sa.Column('monto_bono', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('MXN', 'BRL', 'USD', 'VES', name='moneda'), nullable=False),
    sa.Column('anulado_por_incidencia', sa.Boolean(), nullable=False),
    sa.Column('incidencia_id', sa.Integer(), nullable=True),
    sa.Column('capacitacion_cumplida', sa.Boolean(), nullable=False),
    sa.Column('estatus', sa.Enum('CALCULADA', 'AUTORIZADA', 'PAGADA', name='estatusevaluacion'), nullable=False),
    sa.Column('calculada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incidencia_id'], ['incidencia.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'anio', 'mes')
    )
    op.create_table('resultado_criterio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('criterio_id', sa.Integer(), nullable=False),
    sa.Column('valor_medido', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('umbral', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cumplido', sa.Boolean(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('detalle', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['criterio_id'], ['criterio_estrella.id'], ),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluacion_mensual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_criterio')
    op.drop_table('evaluacion_mensual')
    op.drop_index(op.f('ix_incidencia_fecha'), table_name='incidencia')
    op.drop_table('incidencia')
    op.drop_table('ajuste_comision')
    op.drop_table('comision_consultor')
    op.drop_table('porcentaje_comision')
    op.drop_index(op.f('ix_dia_festivo_fecha'), table_name='dia_festivo')
    op.drop_table('dia_festivo')
    op.drop_table('criterio_estrella')
    # ### end Alembic commands ###
