"""cotizacion y cierre

Revision ID: c2620634c068
Revises: 03a2181c86e9
Create Date: 2026-09-12 04:42:30.643752
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2620634c068'
down_revision: Union[str, None] = '03a2181c86e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cierre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('abierto_en', sa.DateTime(), nullable=False),
    sa.Column('limite_consultor', sa.DateTime(), nullable=False),
    sa.Column('estatus', sa.Enum('ABIERTO', 'EN_REVISION_IA', 'ENVIADO_FINANZAS', 'DEVUELTO_A_OPERACION', 'APROBADO', 'FACTURADO', name='estatuscierre'), nullable=False),
    sa.Column('total_cotizado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_ejecutado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.Column('cerrado_por_id', sa.Integer(), nullable=True),
    sa.Column('dentro_de_plazo', sa.Boolean(), nullable=True),
    sa.Column('devuelto_motivo', sa.String(length=500), nullable=True),
    sa.Column('aprobado_en', sa.DateTime(), nullable=True),
    sa.Column('aprobado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['cerrado_por_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id')
    )
    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tarifario_id', sa.Integer(), nullable=False),
    sa.Column('moneda', sa.Enum('MXN', 'BRL', 'USD', 'VES', name='moneda'), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('viaticos_incluidos', sa.Boolean(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estatus', sa.Enum('BORRADOR', 'ENVIADA', 'AUTORIZADA', 'RECHAZADA', 'SUSTITUIDA', name='estatuscotizacion'), nullable=False),
    sa.Column('motivo_recotizacion', sa.String(length=400), nullable=True),
    sa.Column('creada_por_id', sa.Integer(), nullable=True),
    sa.Column('autorizada_en', sa.DateTime(), nullable=True),
    sa.Column('autorizada_por', sa.String(length=160), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creada_por_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.ForeignKeyConstraint(['tarifario_id'], ['tarifario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desviacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cierre_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('DIAS_DE_MAS', 'DIAS_DE_MENOS', 'RECURSO_NO_COTIZADO', 'HORAS_EXTRA', 'VIATICO_EXCEDIDO', 'VIATICO_SIN_COMPROBAR', 'VIATICO_NO_CERRADO', 'COBRO_MENOR', name='tipodesviacion'), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('respaldada', sa.Boolean(), nullable=False),
    sa.Column('justificacion', sa.String(length=500), nullable=True),
    sa.Column('escalada', sa.Boolean(), nullable=False),
    sa.Column('detectada_por', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['cierre_id'], ['cierre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linea_cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('equipo_clave', sa.String(length=40), nullable=False),
    sa.Column('modalidad_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('RECURSO', 'VEHICULO', 'VIATICOS', name='tipolinea'), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_vehiculo.id'], ),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.id'], ),
    sa.ForeignKeyConstraint(['modalidad_id'], ['modalidad.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_personal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linea_cotizacion')
    op.drop_table('desviacion')
    op.drop_table('cotizacion')
    op.drop_table('cierre')
    # ### end Alembic commands ###
