"""task sheet por equipo

Revision ID: e8ea5b992701
Revises: 19a52685f77e
Create Date: 2026-09-12 06:16:42.377400
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8ea5b992701'
down_revision: Union[str, None] = '19a52685f77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_sheet', sa.Column('equipo_id', sa.Integer(), nullable=False))
    op.drop_constraint('task_sheet_servicio_id_version_key', 'task_sheet', type_='unique')
    op.create_unique_constraint(None, 'task_sheet', ['equipo_id', 'version'])
    op.create_foreign_key(None, 'task_sheet', 'equipo', ['equipo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_sheet', type_='foreignkey')
    op.drop_constraint(None, 'task_sheet', type_='unique')
    op.create_unique_constraint('task_sheet_servicio_id_version_key', 'task_sheet', ['servicio_id', 'version'])
    op.drop_column('task_sheet', 'equipo_id')
    # ### end Alembic commands ###
