"""servicios implantados

Revision ID: fe78fc203ee6
Revises: c2620634c068
Create Date: 2026-09-12 04:56:21.925660
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe78fc203ee6'
down_revision: Union[str, None] = 'c2620634c068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_implantado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('esquema', sa.Enum('POR_DIA', 'MES_COMPLETO', name='esquemacotizacionimplantado'), nullable=False),
    sa.Column('incluye_fines_de_semana', sa.Boolean(), nullable=False),
    sa.Column('dias_base', sa.Integer(), nullable=False),
    sa.Column('hora_presentacion', sa.String(length=8), nullable=False),
    sa.Column('modalidad_id', sa.Integer(), nullable=False),
    sa.Column('titular_id', sa.Integer(), nullable=True),
    sa.Column('titular_rotacion_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('precio_mes_vehiculo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_dia_personal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_dia_adicional', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_mes_completo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('generado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['modalidad_id'], ['modalidad.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.ForeignKeyConstraint(['titular_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['titular_rotacion_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id', 'anio', 'mes')
    )
    op.create_table('reemplazo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('entra_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Enum('DESCANSO', 'ENFERMEDAD', 'CONTINGENCIA', 'BAJA', name='motivoreemplazo'), nullable=False),
    sa.Column('nota', sa.String(length=400), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entra_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Las jornadas que ya existen no son dias adicionales: se les pone false.
    op.add_column('jornada', sa.Column('es_dia_adicional', sa.Boolean(),
                                       nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jornada', 'es_dia_adicional')
    op.drop_table('reemplazo')
    op.drop_table('contrato_implantado')
    # ### end Alembic commands ###
